
import type { Course, Trainer, Book, Testimonial, NewsArticle } from './types';

export const ALL_COURSES: Course[] = [
  {
    id: 'c7',
    slug: 'python-basics',
    title: 'دورة تعلم أساسيات بايثون',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['popular', 'discount'],
    imageId: 'course-python-basics',
    description: 'التعرف على لغة بايثون، المتغيرات، الشروط، التكرار، الدوال.',
    outline: ['مقدمة إلى لغة بايثون', 'المتغيرات وأنواع البيانات', 'العمليات الحسابية والمنطقية', 'الجمل الشرطية والتكرارية', 'الدوال والوظائف'],
    studentReviews: [
        { id: 'csr-py-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-py-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-py-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-py-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-py-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-py-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-py-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-py-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-py-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-py-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c8',
    slug: 'csharp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C#)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-csharp-console',
    description: 'تعلم مفاهيم البرمجة باستخدام C# في بيئة الكونسول.',
    outline: ['إعداد بيئة العمل', 'أساسيات C#', 'البرمجة كائنية التوجه (OOP)', 'التعامل مع الملفات', 'مشروع تطبيقي'],
    studentReviews: [
        { id: 'csr-cs-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-cs-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-cs-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cs-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-cs-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-cs-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-cs-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-cs-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-cs-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cs-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c9',
    slug: 'sql-intro',
    title: 'دورة مقدمة في قواعد البيانات SQL',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    imageId: 'course-sql-intro',
    description: 'مقدمة عملية في أوامر SQL الأساسية لإدارة البيانات.',
    outline: ['مفاهيم قواعد البيانات', 'لغة الاستعلام الهيكلية (SQL)', 'إنشاء وتعديل الجداول', 'الاستعلام عن البيانات (SELECT)', 'ربط الجداول (JOIN)'],
    studentReviews: [
        { id: 'csr-sql-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-sql-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-sql-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-sql-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-sql-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-sql-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-sql-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-sql-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-sql-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-sql-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c10',
    slug: 'windows-forms-csharp',
    title: 'دورة البرمجة المرئية باستخدام Windows Forms',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    imageId: 'course-winforms',
    description: 'تصميم واجهات تطبيقات سطح المكتب باستخدام C#.',
    outline: ['مقدمة إلى Windows Forms', 'الأدوات والعناصر', 'برمجة الأحداث', 'بناء تطبيق متكامل', 'نشر التطبيق'],
    studentReviews: [
        { id: 'csr-wf-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-wf-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-wf-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-wf-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-wf-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-wf-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-wf-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-wf-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-wf-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-wf-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c11',
    slug: 'linux-ubuntu',
    title: 'دورة نظام التشغيل لينكس توزيعة Ubuntu',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-linux',
    description: 'أساسيات نظام التشغيل لينكس وبيئة الأوامر.',
    outline: ['تاريخ لينكس', 'واجهة سطر الأوامر (CLI)', 'إدارة الملفات والمجلدات', 'صلاحيات المستخدمين', 'البرمجة النصية (Shell Scripting)'],
    studentReviews: [
        { id: 'csr-lu-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-lu-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-lu-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-lu-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-lu-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-lu-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-lu-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-lu-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-lu-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-lu-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c12',
    slug: 'ms-project-intro',
    title: 'دورة مقدمة في إدارة المشاريع باستخدام Microsoft Project',
    category: 'إدارة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-ms-project',
    description: 'تعلم التخطيط وإدارة المشاريع باحترافية عبر برنامج Microsoft Project.',
    outline: ['مبادئ إدارة المشاريع', 'واجهة Microsoft Project', 'إنشاء وتخطيط المشاريع', 'متابعة التقدم', 'إصدار التقارير'],
    studentReviews: [
        { id: 'csr-msp-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-msp-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-msp-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-msp-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-msp-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-msp-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-msp-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-msp-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-msp-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-msp-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c13',
    slug: 'cpp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C++)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.6,
    imageId: 'course-cpp-console',
    description: 'مقدمة في البرمجة باستخدام لغة C++ والبرمجة الكائنية.',
    outline: ['أساسيات C++', 'المؤشرات والذاكرة', 'البرمجة الكائنية (OOP)', 'المكتبة القياسية (STL)', 'تطبيقات عملية'],
    studentReviews: [
        { id: 'csr-cpp-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-cpp-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-cpp-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cpp-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-cpp-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-cpp-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-cpp-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-cpp-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-cpp-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cpp-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c14',
    slug: 'web-intro-html-css',
    title: 'دورة مقدمة في الويب (HTML + CSS)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-html-css',
    description: 'تعلم تصميم الصفحات وبناء مواقع ويب أساسية.',
    outline: ['بنية صفحة الويب (HTML)', 'تنسيق الصفحة (CSS)', 'التصميم المتجاوب (Responsive Design)', 'نشر موقع بسيط', 'أفضل الممارسات'],
    studentReviews: [
        { id: 'csr-html-1', name: 'أحمد', quote: 'شرح ممتاز ومبسط، استفدت كثيرًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-html-2', name: 'سارة', quote: 'الدورة كانت رائعة والمدرب متعاون جدًا.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-html-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-html-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-html-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-html-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-html-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-html-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-html-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-html-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c15',
    slug: 'intensive-first-aid',
    title: 'دورة الإسعافات الأولية المكثفة',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: '3 أسابيع',
    rating: 4.9,
    imageId: 'course-first-aid',
    description: 'تعلم التعامل مع الحالات الطارئة والإصابات البسيطة. التدريب العملي على الإسعاف الميداني والإنعاش القلبي الرئوي.',
    outline: ['تقييم الحالات الطارئة', 'التعامل مع الجروح والنزيف', 'الإنعاش القلبي الرئوي (CPR)', 'تثبيت الكسور', 'الإسعافات الأولية للحروق والاختناق'],
    studentReviews: [
      { id: 'csr-fa-1', name: 'أحمد', quote: 'دورة لا غنى عنها، المدرب كان رائعًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-fa-2', name: 'سارة', quote: 'أشعر بثقة أكبر في التعامل مع الطوارئ الآن.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-fa-3', name: 'علي', quote: 'محتوى الدورة قيم والتطبيق العملي مفيد.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-fa-4', name: 'فاطمة', quote: 'أنصح بهذه الدورة للجميع.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-fa-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-fa-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-fa-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-fa-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-fa-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-fa-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c16',
    slug: 'medical-program',
    title: 'دورة البرنامج الطبي',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: 'شهران',
    rating: 4.8,
    imageId: 'course-medical-program',
    description: 'برنامج متكامل لتأهيل الكوادر الطبية والإدارية في المراكز الصحية. يشمل التدريب على النماذج الطبية، استقبال المرضى، وتنظيم السجلات.',
    outline: ['إدارة المراكز الصحية', 'أساسيات استقبال المرضى', 'تنظيم السجلات الطبية', 'التعامل مع النماذج الطبية', 'مهارات التواصل مع المرضى'],
    studentReviews: [
      { id: 'csr-mp-1', name: 'أحمد', quote: 'دورة شاملة ومفيدة جدًا للعاملين في القطاع الصحي.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-mp-2', name: 'سارة', quote: 'المدرب كان ممتازًا والمحتوى منظم.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-mp-3', name: 'علي', quote: 'اكتسبت مهارات إدارية مهمة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mp-4', name: 'فاطمة', quote: 'أنصح بها بشدة.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-mp-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-mp-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-mp-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-mp-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-mp-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mp-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c17',
    slug: 'medical-terminology',
    title: 'دورة المصطلحات الطبية',
    category: 'الطب',
    trainerName: 'د. معتز اليزيدي',
    trainerSlug: 'moataz-al-yazidi',
    duration: 'شهران',
    rating: 4.7,
    imageId: 'course-medical-terminology',
    description: 'تهدف إلى تمكين المتدربين من فهم المصطلحات الطبية باللغة الإنجليزية. تدريب على النطق الصحيح وفهم السياق السريري.',
    outline: ['مقدمة في المصطلحات الطبية', 'مصطلحات أجهزة الجسم', 'مصطلحات الأمراض والعمليات', 'النطق الصحيح للمصطلحات', 'تطبيقات عملية في سياقات سريرية'],
    studentReviews: [
      { id: 'csr-mt-1', name: 'أحمد', quote: 'الدورة ساعدتني كثيرًا في دراستي الطبية.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-mt-2', name: 'سارة', quote: 'المدرب كان ممتازًا والشرح واضح.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-mt-3', name: 'علي', quote: 'محتوى قيم ومفيد.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mt-4', name: 'فاطمة', quote: 'أنصح بها لطلاب الطب.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-mt-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-mt-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-mt-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-mt-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-mt-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mt-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c18',
    slug: 'content-creation-diploma',
    title: 'دبلوم صناعة المحتوى والتسويق الرقمي',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: 'شهر واحد',
    rating: 4.9,
    tags: ['popular', 'discount'],
    imageId: 'course-content-creation',
    description: 'تعلم استراتيجيات صناعة المحتوى الإبداعي. التدريب على التسويق عبر السوشيال ميديا وإدارة الحملات الرقمية.',
    outline: ['استراتيجيات المحتوى الرقمي', 'كتابة المحتوى الإبداعي', 'التسويق عبر وسائل التواصل الاجتماعي', 'إدارة الحملات الإعلانية', 'تحليل الأداء (Analytics)'],
    studentReviews: [
      { id: 'csr-cc-1', name: 'أحمد', quote: 'دورة ممتازة فتحت لي آفاقًا جديدة في التسويق.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-cc-2', name: 'سارة', quote: 'المدرب خبير والمحتوى عملي ومفيد.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cc-3', name: 'علي', quote: 'استفدت كثيرًا من التطبيقات العملية.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cc-4', name: 'فاطمة', quote: 'أنصح بها لكل من يريد دخول عالم التسويق الرقمي.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-cc-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-cc-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-cc-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-cc-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cc-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cc-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c19',
    slug: 'content-marketing',
    title: 'دورة التسويق بالمحتوى',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: '3 أيام',
    rating: 4.8,
    imageId: 'course-content-marketing',
    description: 'التعرف على أساليب كتابة محتوى تسويقي فعال. تطبيق عملي على بناء خطة محتوى لعلامة تجارية.',
    outline: ['مقدمة في التسويق بالمحتوى', 'تحديد الجمهور المستهدف', 'كتابة محتوى جذاب', 'توزيع المحتوى', 'بناء خطة محتوى'],
    studentReviews: [
        { id: 'csr-cm-1', name: 'أحمد', quote: 'دورة مختصرة ومفيدة جدًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-cm-2', name: 'سارة', quote: 'المدرب كان رائعًا والمحتوى قيم.', rating: 4, imageId: 'testimonial-2' },
        { id: 'csr-cm-3', name: 'علي', quote: 'استفدت من بناء خطة المحتوى.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cm-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-cm-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-cm-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-cm-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-cm-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-cm-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-cm-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c20',
    slug: 'autocad',
    title: 'دورة برنامج AutoCAD',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 4.9,
    imageId: 'course-autocad',
    description: 'تعلم أساسيات الرسم الهندسي ثنائي وثلاثي الأبعاد باستخدام AutoCAD. مشاريع تطبيقية على مخططات معمارية حقيقية.',
    outline: ['مقدمة لواجهة AutoCAD', 'أدوات الرسم ثنائي الأبعاد', 'الرسم ثلاثي الأبعاد', 'إعداد المخططات للطباعة', 'مشروع تطبيقي'],
    studentReviews: [
      { id: 'csr-ac-1', name: 'أحمد', quote: 'الدورة كانت ممتازة والمدرب محترف.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-ac-2', name: 'سارة', quote: 'استفدت كثيرًا من المشاريع العملية.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-ac-3', name: 'علي', quote: 'شرح واضح ومبسط.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ac-4', name: 'فاطمة', quote: 'أنصح بها لطلاب الهندسة.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-ac-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-ac-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-ac-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-ac-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-ac-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ac-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c21',
    slug: 'revit-lumion',
    title: 'دورة برنامج Revit + Lumion',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 5.0,
    tags: ['popular', 'discount'],
    imageId: 'course-revit-lumion',
    description: 'تعلم تصميم النماذج ثلاثية الأبعاد باستخدام Revit. استخدام Lumion لعمل الإخراج النهائي والعروض التفاعلية للمشاريع.',
    outline: ['مقدمة في BIM و Revit', 'نمذجة العناصر المعمارية', 'التحضير للتصدير إلى Lumion', 'الإضاءة والمواد في Lumion', 'إنشاء صور ومقاطع فيديو واقعية'],
    studentReviews: [
      { id: 'csr-rl-1', name: 'أحمد', quote: 'أفضل دورة في الإظهار المعماري.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-rl-2', name: 'سارة', quote: 'المدرب كان مذهلاً والمحتوى خرافي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-rl-3', name: 'علي', quote: 'تعلمت مهارات ستغير مسيرتي المهنية.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-rl-4', name: 'فاطمة', quote: 'الدورة تستحق كل ريال.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-rl-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 5, imageId: 'testimonial-5' },
      { id: 'csr-rl-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-rl-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-rl-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-rl-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-rl-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 5, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c22',
    slug: 'interior-design-decoration',
    title: 'دورة التصميم الداخلي والديكور',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: '8 أيام',
    rating: 4.9,
    imageId: 'course-interior-design',
    description: 'تعلم أساسيات التصميم الداخلي وتنسيق الديكور للمساحات السكنية والتجارية.',
    outline: ['مبادئ التصميم الداخلي', 'نظريات الألوان وتطبيقاتها', 'توزيع الأثاث والإضاءة', 'اختيار المواد والتشطيبات', 'مشروع تصميم متكامل'],
    studentReviews: [
      { id: 'csr-id-1', name: 'أحمد', quote: 'الدورة ألهمتني كثيرًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-id-2', name: 'سارة', quote: 'المدرب كان مبدعًا والمحتوى غني.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-id-3', name: 'علي', quote: 'تعلمت كيف أفكر كمصمم داخلي.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-id-4', name: 'فاطمة', quote: 'أنصح بها لكل محبي الديكور.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-id-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-id-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-id-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-id-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-id-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-id-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c23',
    slug: 'photoshop-basics',
    title: 'دورة أساسيات الفوتوشوب',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: 'شهران',
    rating: 4.8,
    imageId: 'course-photoshop',
    description: 'تعلم أدوات Photoshop من الصفر حتى الاحتراف. تدريب عملي على تصميم الشعارات، البوسترات، وتحرير الصور.',
    outline: ['مقدمة لواجهة فوتوشوب', 'الطبقات والأقنعة', 'أدوات التحديد والتحرير', 'تصميم الشعارات والبوسترات', 'مشاريع تطبيقية'],
    studentReviews: [
      { id: 'csr-ps-1', name: 'أحمد', quote: 'الدورة كانت بداية رائعة لي في عالم التصميم.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-ps-2', name: 'سارة', quote: 'المدرب كان صبورًا وشرحه واضح.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-ps-3', name: 'علي', quote: 'استفدت من التطبيقات العملية.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ps-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-ps-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-ps-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-ps-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-ps-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-ps-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ps-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c24',
    slug: 'graphic-design-diploma',
    title: 'دبلوم الجرافيك ديزاين',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: '5 أسابيع',
    rating: 4.9,
    tags: ['popular', 'discount'],
    imageId: 'course-graphic-design-diploma',
    description: 'يشمل برامج التصميم الأساسية (Photoshop, Illustrator, InDesign). تدريب على الهوية البصرية وتصميم العلامات التجارية.',
    outline: ['أساسيات Photoshop', 'تصميم المتجهات ببرنامج Illustrator', 'تصميم المطبوعات ببرنامج InDesign', 'بناء الهوية البصرية', 'مشروع التخرج'],
    studentReviews: [
      { id: 'csr-gd-1', name: 'أحمد', quote: 'دبلوم شامل ومكثف، تعلمت الكثير.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-gd-2', name: 'سارة', quote: 'المدرب كان مبدعًا وملهمًا.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-gd-3', name: 'علي', quote: 'المشروع النهائي كان تحديًا ممتعًا.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-gd-4', name: 'فاطمة', quote: 'أنصح به بشدة لكل من يريد احتراف التصميم.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-gd-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-gd-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-gd-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-gd-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-gd-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-gd-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c25',
    slug: 'graphics-diploma',
    title: 'دبلوم الجرافيكس',
    category: 'التصميم والرسم',
    trainerName: 'م. أحمد بخيت',
    trainerSlug: 'ahmed-bakhit',
    duration: 'شهران',
    rating: 4.7,
    imageId: 'course-graphics-diploma',
    description: 'تعلم التصميم المتقدم والإخراج الإبداعي للمشاريع. يشمل التدريب على أدوات العرض الاحترافي والتصميم الإعلاني.',
    outline: ['تقنيات متقدمة في Photoshop', 'الرسم الرقمي المتقدم', 'موشن جرافيك بسيط', 'تصميم الحملات الإعلانية', 'بناء معرض أعمال احترافي'],
    studentReviews: [
      { id: 'csr-gx-1', name: 'أحمد', quote: 'دورة متقدمة ومفيدة.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-gx-2', name: 'سارة', quote: 'المدرب كان خبيرًا والمحتوى قيم.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-gx-3', name: 'علي', quote: 'تعلمت تقنيات جديدة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-gx-4', name: 'فاطمة', quote: 'أنصح بها للمصممين.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-gx-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-gx-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-gx-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-gx-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-gx-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-gx-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c26',
    slug: 'ai-design',
    title: 'دورة التصميم بالذكاء الاصطناعي',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: '10 أيام',
    rating: 5.0,
    tags: ['popular'],
    imageId: 'course-ai-design',
    description: 'تدريب على استخدام أدوات الذكاء الاصطناعي في التصميم (Midjourney, Canva AI, Firefly). مشاريع عملية لتصميم محتوى احترافي بسرعة وابتكار.',
    outline: ['مقدمة للتصميم التوليدي', 'استخدام Midjourney لإنشاء صور', 'التصميم السريع باستخدام Canva AI', 'تحرير وتوسيع الصور مع Firefly', 'تطبيقات عملية في التسويق'],
    studentReviews: [
        { id: 'csr-aid-1', name: 'أحمد', quote: 'دورة مستقبلية ومدهشة!', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-aid-2', name: 'سارة', quote: 'المدرب كان رائعًا والتطبيقات عملية.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-aid-3', name: 'علي', quote: 'فتحت عيني على إمكانيات جديدة.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-aid-4', name: 'فاطمة', quote: 'أنصح بها لكل مصمم يريد مواكبة التطور.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-aid-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 5, imageId: 'testimonial-5' },
        { id: 'csr-aid-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-aid-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-aid-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-aid-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-aid-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 5, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c27',
    slug: 'photography-editing',
    title: 'دورة فن التصوير والمونتاج',
    category: 'التصميم والرسم',
    trainerName: 'أ. فاطمة باجبير',
    trainerSlug: 'fatima-bajaber',
    duration: '6 أيام',
    rating: 4.8,
    imageId: 'course-photography-editing',
    description: 'تعلم أساسيات التصوير الفوتوغرافي والفيديو. تدريب عملي على المونتاج باستخدام برامج احترافية.',
    outline: ['أساسيات الكاميرا والإضاءة', 'قواعد التكوين في التصوير', 'مبادئ المونتاج والتحرير', 'العمل على برامج المونتاج', 'مشروع فيلم قصير'],
    studentReviews: [
      { id: 'csr-pe-1', name: 'أحمد', quote: 'الدورة كانت ممتعة ومفيدة.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-pe-2', name: 'سارة', quote: 'المدربة كانت رائعة والشرح واضح.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-pe-3', name: 'علي', quote: 'استفدت من الجانب العملي.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-pe-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-pe-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-pe-6', name: 'مريم', quote: 'المدربة متمكنة والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-pe-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-pe-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-pe-9', name: 'يوسف', quote: 'شكرًا للمدربة على جهودها.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-pe-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c28',
    slug: 'mobile-photography',
    title: 'دورة أساسيات التصوير بالجوال',
    category: 'التصميم والرسم',
    trainerName: 'أ. وليد باكركر',
    trainerSlug: 'waleed-bakarkar',
    duration: 'يومان',
    rating: 4.9,
    imageId: 'course-mobile-photography',
    description: 'تعلم كيفية التقاط صور احترافية بالجوال. نصائح في الإضاءة، الزوايا، والتحرير عبر تطبيقات الهاتف.',
    outline: ['ضبط إعدادات كاميرا الجوال', 'استغلال الإضاءة الطبيعية', 'قواعد التكوين البصري', 'تطبيقات تحرير الصور', 'جلسة تصوير عملية'],
    studentReviews: [
        { id: 'csr-mp-1', name: 'أحمد', quote: 'دورة قصيرة ومكثفة ومفيدة جدًا.', rating: 5, imageId: 'testimonial-1' },
        { id: 'csr-mp-2', name: 'سارة', quote: 'المدرب كان رائعًا وأعطانا نصائح ذهبية.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-mp-3', name: 'علي', quote: 'تغيرت نظرتي للتصوير بالجوال.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-mp-4', name: 'فاطمة', quote: 'أنصح بها بشدة.', rating: 5, imageId: 'testimonial-4' },
        { id: 'csr-mp-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
        { id: 'csr-mp-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
        { id: 'csr-mp-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
        { id: 'csr-mp-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
        { id: 'csr-mp-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
        { id: 'csr-mp-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c29',
    slug: 'cyber-security',
    title: 'دورة الأمن السيبراني',
    category: 'الأمن السيبراني',
    trainerName: 'م. محسن العطاس',
    trainerSlug: 'mohsen-alattas',
    duration: '10 أيام',
    rating: 4.9,
    tags: ['online'],
    imageId: 'course-cyber-security',
    description: 'مقدمة شاملة في مفاهيم الأمن السيبراني وحماية البيانات. تدريب عملي على اكتشاف الثغرات وتأمين الأنظمة.',
    outline: ['مفاهيم أساسية في الأمن السيبراني', 'أنواع الهجمات الشائعة', 'تأمين الشبكات والأنظمة', 'اكتشاف الثغرات', 'الاستجابة للحوادث الأمنية'],
    studentReviews: [
      { id: 'csr-cy-1', name: 'أحمد', quote: 'دورة مهمة جدًا في هذا العصر.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-cy-2', name: 'سارة', quote: 'المدرب خبير والمحتوى محدث.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cy-3', name: 'علي', quote: 'استفدت من الجانب العملي.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cy-4', name: 'فاطمة', quote: 'أنصح بها لكل مهتم بالتكنولوجيا.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-cy-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-cy-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-cy-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-cy-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cy-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cy-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c30',
    slug: 'mobile-programming',
    title: 'دورة برمجة الجوالات',
    category: 'البرمجة',
    trainerName: 'م. محسن العطاس',
    trainerSlug: 'mohsen-alattas',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['online'],
    imageId: 'course-mobile-dev',
    description: 'تعلم أساسيات تطوير تطبيقات Android وiOS. تدريب على بناء واجهات وتوصيلها بقاعدة البيانات.',
    outline: ['مقدمة لتطوير تطبيقات الجوال', 'أساسيات تطوير Android (Kotlin)', 'أساسيات تطوير iOS (Swift)', 'بناء واجهات مستخدم تفاعلية', 'ربط التطبيق بقاعدة بيانات'],
    studentReviews: [
      { id: 'csr-md-1', name: 'أحمد', quote: 'الدورة كانت بداية ممتازة لي في برمجة الجوال.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-md-2', name: 'سارة', quote: 'المدرب كان متعاونًا جدًا.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-md-3', name: 'علي', quote: 'استفدت من بناء التطبيق العملي.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-md-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-md-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-md-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-md-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-md-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-md-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-md-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c31',
    slug: 'secretarial-office-management',
    title: 'دورة السكرتارية وإدارة المكاتب',
    category: 'السكرتارية',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: '10 أيام',
    rating: 4.7,
    tags: ['online'],
    imageId: 'course-secretarial',
    description: 'تأهيل المتدربين على مهارات السكرتارية الحديثة وتنظيم المكاتب. التدريب على المراسلات وإدارة الاجتماعات وتنظيم الملفات.',
    outline: ['مهام السكرتير التنفيذي', 'إدارة الوقت وتنظيم المهام', 'فن المراسلات التجارية', 'تنظيم الاجتماعات وكتابة المحاضر', 'الأرشفة الإلكترونية والورقية'],
    studentReviews: [
      { id: 'csr-so-1', name: 'أحمد', quote: 'دورة عملية ومفيدة جدًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-so-2', name: 'سارة', quote: 'المدرب كان رائعًا والمحتوى منظم.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-so-3', name: 'علي', quote: 'اكتسبت مهارات تنظيمية ممتازة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-so-4', name: 'فاطمة', quote: 'أنصح بها لكل من يعمل في مجال الإدارة.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-so-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-so-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-so-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-so-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-so-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-so-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c32',
    slug: 'customer-service',
    title: 'دورة خدمة العملاء',
    category: 'خدمة العملاء',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['online'],
    imageId: 'course-customer-service',
    description: 'تعلم مهارات التواصل الفعّال مع العملاء وإدارة المواقف الصعبة. تطوير مهارات الإنصات واللباقة المهنية.',
    outline: ['أهمية خدمة العملاء', 'مهارات التواصل الفعال', 'التعامل مع شكاوى العملاء', 'إدارة المواقف الصعبة', 'بناء علاقات دائمة مع العملاء'],
    studentReviews: [
      { id: 'csr-cs-1', name: 'أحمد', quote: 'الدورة غيرت من طريقة تعاملي مع العملاء.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-cs-2', name: 'سارة', quote: 'المدربة كانت ملهمة والمحتوى قيم.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cs-3', name: 'علي', quote: 'استفدت من لعب الأدوار والمواقف العملية.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cs-4', name: 'فاطمة', quote: 'أنصح بها لكل من يتعامل مع الجمهور.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-cs-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-cs-6', name: 'مريم', quote: 'المدربة متمكنة والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-cs-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-cs-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cs-9', name: 'يوسف', quote: 'شكرًا للمدربة على جهودها.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cs-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c33',
    slug: 'life-coach-evening',
    title: 'أمسية مدرب الحياة (Life Coach Evening)',
    category: 'التفكير الإبداعي',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: 'يوم واحد',
    rating: 4.9,
    tags: ['online'],
    imageId: 'course-life-coach',
    description: 'أمسية تطوير ذاتي حول التحفيز والإيجابية وإدارة الحياة. تفاعلية مع جلسة أسئلة وإجابات مباشرة.',
    outline: ['مقدمة في الكوتشينج', 'تحديد الأهداف الشخصية', 'استراتيجيات التحفيز الذاتي', 'التغلب على التحديات', 'جلسة أسئلة وأجوبة'],
    studentReviews: [
      { id: 'csr-lc-1', name: 'أحمد', quote: 'الأمسية كانت ملهمة جدًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-lc-2', name: 'سارة', quote: 'المدربة كانت رائعة.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-lc-3', name: 'علي', quote: 'خرجت بطاقة إيجابية كبيرة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-lc-4', name: 'فاطمة', quote: 'أنصح بها لكل من يبحث عن التغيير.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-lc-5', name: 'حسن', quote: 'تجربة ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-lc-6', name: 'مريم', quote: 'المدربة متمكنة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-lc-7', name: 'خالد', quote: 'استفدت من النصائح.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-lc-8', name: 'نورة', quote: 'الأمسية فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-lc-9', name: 'يوسف', quote: 'شكرًا للمدربة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-lc-10', name: 'زينب', quote: 'محتوى قيم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c34',
    slug: 'creative-thinking-evening',
    title: 'أمسية التفكير الإبداعي',
    category: 'التفكير الإبداعي',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: 'يوم واحد',
    rating: 4.9,
    tags: [],
    imageId: 'course-creative-thinking',
    description: 'تعلم طرق التفكير خارج الصندوق وإطلاق العنان للإبداع. تطبيقات عملية وتمارين تحفيزية.',
    outline: ['ما هو التفكير الإبداعي؟', 'تقنيات العصف الذهني', 'حل المشكلات بطرق مبتكرة', 'تمارين عملية لتحفيز الإبداع', 'تطبيق الأفكار على أرض الواقع'],
    studentReviews: [
      { id: 'csr-ct-1', name: 'أحمد', quote: 'الأمسية كانت رائعة ومحفزة.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-ct-2', name: 'سارة', quote: 'المدربة كانت مبدعة.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-ct-3', name: 'علي', quote: 'تعلمت طرقًا جديدة في التفكير.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ct-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-ct-5', name: 'حسن', quote: 'تجربة ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-ct-6', name: 'مريم', quote: 'المدربة متمكنة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-ct-7', name: 'خالد', quote: 'استفدت من التمارين.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-ct-8', name: 'نورة', quote: 'الأمسية فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-ct-9', name: 'يوسف', quote: 'شكرًا للمدربة.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-ct-10', name: 'زينب', quote: 'محتوى قيم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c35',
    slug: 'computer-diploma',
    title: 'دبلوم الحاسوب',
    category: 'الحاسوب',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: 'شهران',
    rating: 4.8,
    tags: ['popular', 'discount'],
    imageId: 'course-computer-diploma',
    description: 'تدريب شامل على أساسيات الحاسوب وأنظمة التشغيل وبرامج Microsoft Office. يشمل التطبيق العملي في Excel, Word, PowerPoint.',
    outline: ['مكونات الحاسوب وأنظمة التشغيل', 'إتقان برنامج Microsoft Word', 'مهارات متقدمة في Microsoft Excel', 'تصميم عروض تقديمية احترافية بـ PowerPoint', 'أمن المعلومات والإنترنت'],
    studentReviews: [
      { id: 'csr-cd-1', name: 'أحمد', quote: 'الدبلوم كان شاملاً ومفيدًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-cd-2', name: 'سارة', quote: 'المدرب كان رائعًا وشرحه مبسط.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-cd-3', name: 'علي', quote: 'اكتسبت مهارات أساسية في الحاسوب.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cd-4', name: 'فاطمة', quote: 'أنصح به لكل مبتدئ.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-cd-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-cd-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-cd-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-cd-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-cd-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-cd-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c36',
    slug: 'mayo-ketchup-course',
    title: 'دورة المايونيز والكاتشب',
    category: 'دورات نسائية',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: '4 أيام',
    rating: 4.5,
    tags: ['discount'],
    imageId: 'course-mayo-ketchup',
    description: 'دورة عملية لتعلّم طرق إعداد المايونيز والكاتشب بطرق احترافية. مناسبة لمحبات الطبخ والمشاريع المنزلية الصغيرة. تتضمن وصفات ونصائح لتغليف وتخزين المنتجات.',
    outline: ['أساسيات صنع الصلصات', 'وصفة المايونيز الكلاسيكي', 'وصفة الكاتشب المنزلي', 'نصائح التغليف والتخزين', 'أفكار لمشاريع منزلية'],
    studentReviews: [
      { id: 'csr-mk-1', name: 'أحمد', quote: 'الدورة كانت ممتعة ولذيذة!', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-mk-2', name: 'سارة', quote: 'المدرب كان رائعًا والوصفات ناجحة.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-mk-3', name: 'علي', quote: 'استفدت من نصائح المشاريع المنزلية.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mk-4', name: 'فاطمة', quote: 'أنصح بها.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-mk-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-mk-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-mk-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-mk-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-mk-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-mk-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c37',
    slug: 'hairdressing-diploma',
    title: 'دبلوم الكوافير',
    category: 'دورات نسائية',
    trainerName: 'أ. فاطمة باوزير',
    trainerSlug: 'fatima-bawazir',
    duration: 'شهران',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-hairdressing',
    description: 'تأهيل متكامل في تصفيف الشعر والعناية بالبشرة والمكياج. تدريب عملي على أحدث أدوات وصيحات الجمال. يمنح شهادة دبلوم معتمدة بعد اجتياز الاختبارات النهائية.',
    outline: ['أساسيات قص الشعر', 'تقنيات الصبغات الحديثة', 'العناية بالبشرة والمكياج', 'تسريحات المناسبات', 'إدارة صالونات التجميل'],
    studentReviews: [
      { id: 'csr-hd-1', name: 'أحمد', quote: 'الدبلوم كان شاملاً ومفيدًا جدًا.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-hd-2', name: 'سارة', quote: 'المدربة كانت خبيرة والمحتوى احترافي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-hd-3', name: 'علي', quote: 'اكتسبت مهارات حقيقية لسوق العمل.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-hd-4', name: 'فاطمة', quote: 'أنصح به لكل من ترغب في احتراف التجميل.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-hd-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-hd-6', name: 'مريم', quote: 'المدربة متمكنة والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-hd-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-hd-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-hd-9', name: 'يوسف', quote: 'شكرًا للمدربة على جهودها.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-hd-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  },
  {
    id: 'c38',
    slug: 'marketing-360-diploma',
    title: 'دبلوم التسويق 360',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: '3 أسابيع',
    rating: 4.8,
    tags: [],
    imageId: 'course-marketing-360',
    description: 'تعلم استراتيجيات التسويق الشامل عبر المنصات الرقمية والتقليدية. تطبيق عملي على التسويق بالمحتوى والإعلانات الممولة. مناسب لرائدات الأعمال والراغبات في تنمية مشاريعهن.',
    outline: ['مقدمة في التسويق الشامل', 'استراتيجيات التسويق الرقمي', 'التسويق عبر وسائل التواصل الاجتماعي', 'الإعلانات الممولة (Google & Meta)', 'التسويق التقليدي والتكامل'],
    studentReviews: [
      { id: 'csr-m360-1', name: 'أحمد', quote: 'دبلوم ممتاز وغني بالمعلومات.', rating: 5, imageId: 'testimonial-1' },
      { id: 'csr-m360-2', name: 'سارة', quote: 'المدرب كان رائعًا والمحتوى عملي.', rating: 4, imageId: 'testimonial-2' },
      { id: 'csr-m360-3', name: 'علي', quote: 'استفدت كثيرًا من استراتيجيات التسويق.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-m360-4', name: 'فاطمة', quote: 'أنصح به.', rating: 5, imageId: 'testimonial-4' },
      { id: 'csr-m360-5', name: 'حسن', quote: 'تجربة تعليمية ممتازة.', rating: 4, imageId: 'testimonial-5' },
      { id: 'csr-m360-6', name: 'مريم', quote: 'المدرب متمكن والمادة العلمية منظمة.', rating: 5, imageId: 'testimonial-6' },
      { id: 'csr-m360-7', name: 'خالد', quote: 'استفدت من الأمثلة العملية.', rating: 4, imageId: 'testimonial-1' },
      { id: 'csr-m360-8', name: 'نورة', quote: 'الدورة فاقت توقعاتي.', rating: 5, imageId: 'testimonial-2' },
      { id: 'csr-m360-9', name: 'يوسف', quote: 'شكرًا للمدرب على جهوده.', rating: 5, imageId: 'testimonial-3' },
      { id: 'csr-m360-10', name: 'زينب', quote: 'محتوى قيم وسهل الفهم.', rating: 4, imageId: 'testimonial-4' },
    ],
  }
];

export const LATEST_COURSES = ALL_COURSES.slice(0, 3);

export const ALL_TRAINERS: Trainer[] = [
  {
    id: 't4',
    slug: 'mahmoud-alhasani',
    name: 'م. محمود الحساني',
    field: 'البرمجة',
    rating: 4.8,
    imageId: 'trainer-9',
    bio: 'مدرب برمجة متخصص في نظم المعلومات، يمتلك خبرة واسعة في بناء الأنظمة والتطبيقات. حاصل على العديد من الشهادات الدولية.',
    qualifications: ['بكالوريوس نظم معلومات'],
    accreditations: ['شهادة مطور تطبيقات من Google', 'شهادة تحليل بيانات من IBM', 'شهادة من جامعة ستانفورد', 'والعديد من الشهادات الأخرى'],
    coursesCount: 9,
    studentsCount: 850,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/mahmoud-alhasani', 
      facebook: 'https://www.facebook.com/mahmoud.alhasani',
      instagram: 'https://www.instagram.com/mahmoud.alhasani'
    },
    reviews: [
        { id: 'tr-ma-1', studentName: 'عبدالله العامري', rating: 5, comment: 'شرح المهندس محمود مبسط وواضح جدًا، استفدت كثيرًا من خبرته.', imageId: 'testimonial-1' },
        { id: 'tr-ma-2', studentName: 'سارة خالد', rating: 4, comment: 'دورة بايثون كانت ممتازة، والمهندس متعاون لأبعد حد.', imageId: 'testimonial-2' },
        { id: 'tr-ma-3', studentName: 'أحمد ياسين', rating: 5, comment: 'أفضل مدرب برمجة تعاملت معه، متمكن من مادته العلمية.', imageId: 'testimonial-3' },
        { id: 'tr-ma-4', studentName: 'فاطمة علي', rating: 5, comment: 'لقد جعل مفاهيم البرمجة المعقدة سهلة الفهم.', imageId: 'testimonial-4' },
        { id: 'tr-ma-5', studentName: 'حسن محمد', rating: 4, comment: 'أنصح بدوراته بشدة.', imageId: 'testimonial-5' },
        { id: 'tr-ma-6', studentName: 'مريم صالح', rating: 5, comment: 'مدرب محترف وصبور، يجيب على كل الأسئلة بصدر رحب.', imageId: 'testimonial-6' },
        { id: 'tr-ma-7', studentName: 'خالد سالم', rating: 4, comment: 'استفدت من التطبيقات العملية التي قدمها.', imageId: 'testimonial-1' },
        { id: 'tr-ma-8', studentName: 'نورة عبدالله', rating: 5, comment: 'دورة قواعد البيانات كانت الأفضل على الإطلاق.', imageId: 'testimonial-2' },
        { id: 'tr-ma-9', studentName: 'يوسف حسن', rating: 5, comment: 'شكرًا مهندس محمود، لقد كانت تجربة تعليمية فريدة.', imageId: 'testimonial-3' },
        { id: 'tr-ma-10', studentName: 'زينب أحمد', rating: 4, comment: 'محتوى غني وأسلوب شيق.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't5',
    slug: 'ali-bajamaza',
    name: 'د. علي باجامزة',
    field: 'الطب',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'طبيب ومحاضر متخصص في طب الطوارئ. يمتلك خبرة طويلة في تدريب الكوادر الطبية على الإسعافات الأولية والتعامل مع الحالات الحرجة.',
    qualifications: ['دكتوراة في طب الطوارئ', 'مدرب معتمد في الإنعاش القلبي الرئوي'],
    accreditations: ['البورد العربي في طب الطوارئ'],
    coursesCount: 15,
    studentsCount: 950,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/ali-bajamaza', 
      facebook: 'https://www.facebook.com/ali.bajamaza'
    },
    reviews: [
       { id: 'tr-ab-1', studentName: 'فاطمة النهدي', rating: 5, comment: 'الدكتور علي مدرب متمكن ومتميزة في تبسيط المعلومات الطبية المعقدة. كانت الدورة عملية ومفيدة جدًا.', imageId: 'testimonial-2' },
       { id: 'tr-ab-2', studentName: 'أحمد العامري', rating: 5, comment: 'دورة الإسعافات الأولية كانت من أفضل الدورات التي حضرتها، شكرًا دكتور.', imageId: 'testimonial-1' },
       { id: 'tr-ab-3', studentName: 'سارة سالم', rating: 4, comment: 'أسلوب الدكتور في الشرح رائع والمادة العلمية قيمة.', imageId: 'testimonial-2' },
       { id: 'tr-ab-4', studentName: 'محمد عبدالله', rating: 5, comment: 'أشعر الآن بثقة أكبر في التعامل مع الحالات الطارئة.', imageId: 'testimonial-3' },
       { id: 'tr-ab-5', studentName: 'عائشة حسن', rating: 5, comment: 'مدرب استثنائي، أنصح الجميع بحضور دوراته.', imageId: 'testimonial-4' },
       { id: 'tr-ab-6', studentName: 'علي محمد', rating: 4, comment: 'التدريب العملي كان مفيدًا للغاية.', imageId: 'testimonial-5' },
       { id: 'tr-ab-7', studentName: 'مريم أحمد', rating: 5, comment: 'شكرًا جزيلًا للدكتور علي على كل المعلومات القيمة.', imageId: 'testimonial-6' },
       { id: 'tr-ab-8', studentName: 'خالد صالح', rating: 4, comment: 'دورة ممتازة وتستحق الحضور.', imageId: 'testimonial-1' },
       { id: 'tr-ab-9', studentName: 'نورة علي', rating: 5, comment: 'من أفضل المدربين في المجال الطبي.', imageId: 'testimonial-2' },
       { id: 'tr-ab-10', studentName: 'يوسف خالد', rating: 5, comment: 'تجربة تعليمية لا تنسى.', imageId: 'testimonial-3' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't7',
    slug: 'salem-bajulaida',
    name: 'أ. سالم باجليدة',
    field: 'التسويق',
    rating: 4.9,
    imageId: 'trainer-7',
    bio: 'خبير تسويق رقمي وصانع محتوى. يساعد الشركات والأفراد على بناء حضور قوي عبر الإنترنت من خلال استراتيجيات محتوى فعالة.',
    qualifications: ['ماجستير في إدارة الأعمال (تخصص تسويق)'],
    accreditations: ['شهادة تسويق المحتوى من HubSpot', 'شهادة إعلانات Google'],
    coursesCount: 20,
    studentsCount: 1200,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/salem-bajulaida', 
      instagram: 'https://www.instagram.com/salem.bajulaida'
    },
    reviews: [
      { id: 'tr-sb-1', studentName: 'علي محمد', rating: 5, comment: 'الأستاذ سالم خبير حقيقي في التسويق الرقمي، دورته كانت نقلة نوعية لي.', imageId: 'testimonial-3' },
      { id: 'tr-sb-2', studentName: 'فاطمة حسن', rating: 5, comment: 'محتوى الدورة كان عمليًا ومباشرًا، استفدت من كل دقيقة.', imageId: 'testimonial-4' },
      { id: 'tr-sb-3', studentName: 'خالد أحمد', rating: 4, comment: 'مدرب رائع ومتمكن، يمتلك قدرة على إيصال المعلومة بسهولة.', imageId: 'testimonial-5' },
      { id: 'tr-sb-4', studentName: 'نورة سالم', rating: 5, comment: 'دورة صناعة المحتوى غيرت طريقة تفكيري في التسويق.', imageId: 'testimonial-6' },
      { id: 'tr-sb-5', studentName: 'عبدالرحمن علي', rating: 5, comment: 'أنصح بشدة بدورات الأستاذ سالم لكل من يرغب في تطوير مهاراته التسويقية.', imageId: 'testimonial-1' },
      { id: 'tr-sb-6', studentName: 'مريم عبدالله', rating: 4, comment: 'تجربة تعليمية ملهمة.', imageId: 'testimonial-2' },
      { id: 'tr-sb-7', studentName: 'ياسر محمد', rating: 5, comment: 'من أفضل المدربين الذين تعاملت معهم.', imageId: 'testimonial-3' },
      { id: 'tr-sb-8', studentName: 'آمنة خالد', rating: 5, comment: 'المحتوى كان غنيًا جدًا والتطبيقات العملية مفيدة.', imageId: 'testimonial-4' },
      { id: 'tr-sb-9', studentName: 'عمر صالح', rating: 4, comment: 'شكرًا للأستاذ سالم على جهوده الرائعة.', imageId: 'testimonial-5' },
      { id: 'tr-sb-10', studentName: 'زينب ياسر', rating: 5, comment: 'الدورة فاقت كل توقعاتي.', imageId: 'testimonial-6' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't6',
    slug: 'moataz-al-yazidi',
    name: 'د. معتز اليزيدي',
    field: 'الطب واللغات',
    rating: 4.8,
    imageId: 'trainer-3',
    bio: 'صيدلاني ومترجم طبي. متخصص في تدريس المصطلحات الطبية للناطقين بغير الإنجليزية، ويجمع بين الخبرة الطبية واللغوية.',
    qualifications: ['بكالوريوس صيدلة', 'دبلوم في الترجمة الطبية'],
    accreditations: ['عضو جمعية المترجمين العلميين'],
    coursesCount: 10,
    studentsCount: 700,
    socials: { 
      twitter: 'https://twitter.com/moataz-al-yazidi'
    },
    reviews: [
      { id: 'tr-my-1', studentName: 'أحمد سالم', rating: 5, comment: 'دورة المصطلحات الطبية كانت ممتازة، شكرًا دكتور معتز.', imageId: 'testimonial-1' },
      { id: 'tr-my-2', studentName: 'سارة علي', rating: 4, comment: 'أسلوب الدكتور في الشرح رائع.', imageId: 'testimonial-2' },
      { id: 'tr-my-3', studentName: 'محمد حسن', rating: 5, comment: 'استفدت كثيرًا في تحسين لغتي الطبية.', imageId: 'testimonial-3' },
      { id: 'tr-my-4', studentName: 'فاطمة خالد', rating: 5, comment: 'مدرب رائع ومحتوى قيم.', imageId: 'testimonial-4' },
      { id: 'tr-my-5', studentName: 'حسن عبدالله', rating: 4, comment: 'أنصح بالدورة لجميع طلاب الكليات الصحية.', imageId: 'testimonial-5' },
      { id: 'tr-my-6', studentName: 'مريم صالح', rating: 5, comment: 'الدكتور معتز يجمع بين العلم والخبرة.', imageId: 'testimonial-6' },
      { id: 'tr-my-7', studentName: 'خالد محمد', rating: 4, comment: 'تجربة تعليمية ممتازة.', imageId: 'testimonial-1' },
      { id: 'tr-my-8', studentName: 'نورة أحمد', rating: 5, comment: 'شكرًا جزيلًا على هذه الدورة المفيدة.', imageId: 'testimonial-2' },
      { id: 'tr-my-9', studentName: 'يوسف علي', rating: 5, comment: 'من أفضل الدورات التي حضرتها.', imageId: 'testimonial-3' },
      { id: 'tr-my-10', studentName: 'زينب حسن', rating: 4, comment: 'محتوى الدورة كان منظمًا وسهل الفهم.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't8',
    slug: 'adel-al-suwail',
    name: 'م. عادل الصويل',
    field: 'الهندسة',
    rating: 4.9,
    imageId: 'trainer-11',
    bio: 'مهندس معماري ومصمم ثلاثي الأبعاد. متخصص في برامج Autodesk و Lumion، ويعمل على تدريب المهندسين على أحدث التقنيات في التصميم والإظهار المعماري.',
    qualifications: ['بكالوريوس هندسة معمارية'],
    accreditations: ['Autodesk Certified Professional (ACP)', 'Lumion Certified Expert'],
    coursesCount: 18,
    studentsCount: 800,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/adel-al-suwail', 
      website: 'https://adel-designs.com'
    },
    reviews: [
      { id: 'tr-as-1', studentName: 'سليمان خالد', rating: 5, comment: 'المهندس عادل من أفضل المدربين في مجال الهندسة المعمارية، خبرته لا تقدر بثمن.', imageId: 'testimonial-5' },
      { id: 'tr-as-2', studentName: 'عائشة محمد', rating: 5, comment: 'دورة الريفيت كانت مذهلة، تعلمت الكثير في وقت قصير.', imageId: 'testimonial-6' },
      { id: 'tr-as-3', studentName: 'عبدالله صالح', rating: 4, comment: 'أسلوب المهندس في التدريب عملي ومباشر.', imageId: 'testimonial-1' },
      { id: 'tr-as-4', studentName: 'مريم علي', rating: 5, comment: 'دورة التصميم الداخلي كانت ملهمة جدًا.', imageId: 'testimonial-2' },
      { id: 'tr-as-5', studentName: 'أحمد ياسر', rating: 5, comment: 'مدرب محترف بكل معنى الكلمة.', imageId: 'testimonial-3' },
      { id: 'tr-as-6', studentName: 'سارة عبدالله', rating: 4, comment: 'استفدت كثيرًا من خبرته في برنامج Lumion.', imageId: 'testimonial-4' },
      { id: 'tr-as-7', studentName: 'حسن خالد', rating: 5, comment: 'أنصح بدوراته لجميع طلاب وخريجي الهندسة.', imageId: 'testimonial-5' },
      { id: 'tr-as-8', studentName: 'فاطمة أحمد', rating: 5, comment: 'المهندس عادل يجعل البرامج الهندسية سهلة وممتعة.', imageId: 'testimonial-6' },
      { id: 'tr-as-9', studentName: 'علي حسن', rating: 4, comment: 'تجربة رائعة ومفيدة.', imageId: 'testimonial-1' },
      { id: 'tr-as-10', studentName: 'نورة سالم', rating: 5, comment: 'شكرًا للمهندس عادل على كل ما قدمه.', imageId: 'testimonial-2' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't9',
    slug: 'aahed-babaier',
    name: 'أ. عاهد بابعير',
    field: 'التصميم والرسم',
    rating: 4.9,
    imageId: 'trainer-10',
    bio: 'مصمم جرافيك محترف ومبدع، يركز على تعليم فنون التصميم الرقمي واستخدام أدوات الذكاء الاصطناعي لتسريع العملية الإبداعية.',
    qualifications: ['شهادة في التصميم الجرافيكي'],
    accreditations: ['Adobe Certified Expert (ACE)'],
    coursesCount: 12,
    studentsCount: 900,
    socials: {
      linkedin: 'https://www.linkedin.com/in/aahed-babaier',
    },
    reviews: [
      { id: 'tr-ab-1', studentName: 'خديجة علي', rating: 5, comment: 'أستاذ عاهد مدرب استثنائي، دورة الذكاء الاصطناعي في التصميم كانت ثورية.', imageId: 'testimonial-4' },
      { id: 'tr-ab-2', studentName: 'يوسف محمد', rating: 5, comment: 'أسلوبه في الشرح جذاب والمحتوى عملي ومفيد.', imageId: 'testimonial-3' },
      { id: 'tr-ab-3', studentName: 'آمنة حسن', rating: 4, comment: 'تعلمت أدوات جديدة ستساعدني كثيرًا في عملي.', imageId: 'testimonial-2' },
      { id: 'tr-ab-4', studentName: 'سالم أحمد', rating: 5, comment: 'دبلوم الجرافيك كان شاملاً وفتح لي أبوابًا جديدة.', imageId: 'testimonial-1' },
      { id: 'tr-ab-5', studentName: 'فاطمة صالح', rating: 5, comment: 'مدرب مبدع وملهم.', imageId: 'testimonial-4' },
      { id: 'tr-ab-6', studentName: 'علي عبدالله', rating: 4, comment: 'أنصح بدوراته لكل من يهتم بمجال التصميم.', imageId: 'testimonial-5' },
      { id: 'tr-ab-7', studentName: 'مريم خالد', rating: 5, comment: 'تجربة تعليمية فريدة وممتعة.', imageId: 'testimonial-6' },
      { id: 'tr-ab-8', studentName: 'حسن علي', rating: 5, comment: 'الأستاذ عاهد يمتلك شغفًا حقيقيًا بالتصميم وينقله لطلابه.', imageId: 'testimonial-3' },
      { id: 'tr-ab-9', studentName: 'نورة ياسر', rating: 4, comment: 'استفدت كثيرًا من خبرته العملية.', imageId: 'testimonial-2' },
      { id: 'tr-ab-10', studentName: 'أحمد سالم', rating: 5, comment: 'شكرًا أستاذ عاهد على كل شيء.', imageId: 'testimonial-1' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't10',
    slug: 'ahmed-bakhit',
    name: 'م. أحمد بخيت',
    field: 'التصميم والرسم',
    rating: 4.8,
    imageId: 'trainer-13',
    bio: 'مهندس ومصمم جرافيكس متخصص في التصميم المتقدم والإخراج الإبداعي. يمتلك خبرة في تدريب الطلاب على بناء محافظ أعمال احترافية.',
    qualifications: ['بكالوريوس في هندسة الوسائط المتعددة'],
    accreditations: [],
    coursesCount: 8,
    studentsCount: 450,
    socials: {},
    reviews: [
        { id: 'tr-abk-1', studentName: 'محمد علي', rating: 5, comment: 'المهندس أحمد مدرب متمكن ومحترف.', imageId: 'testimonial-1' },
        { id: 'tr-abk-2', studentName: 'عائشة سالم', rating: 4, comment: 'دورة الجرافيكس كانت مفيدة جدًا.', imageId: 'testimonial-2' },
        { id: 'tr-abk-3', studentName: 'ياسر عبدالله', rating: 5, comment: 'استفدت من خبرته في بناء معرض أعمالي.', imageId: 'testimonial-3' },
        { id: 'tr-abk-4', studentName: 'نورة حسن', rating: 5, comment: 'شرحه واضح وأسلوبه مميز.', imageId: 'testimonial-4' },
        { id: 'tr-abk-5', studentName: 'علي أحمد', rating: 4, comment: 'أنصح بدوراته.', imageId: 'testimonial-5' },
        { id: 'tr-abk-6', studentName: 'فاطمة محمد', rating: 5, comment: 'تجربة تعليمية رائعة.', imageId: 'testimonial-6' },
        { id: 'tr-abk-7', studentName: 'سالم خالد', rating: 4, comment: 'محتوى الدورة كان قيمًا.', imageId: 'testimonial-1' },
        { id: 'tr-abk-8', studentName: 'مريم علي', rating: 5, comment: 'المهندس أحمد يساعد الطلاب على إطلاق إبداعهم.', imageId: 'testimonial-2' },
        { id: 'tr-abk-9', studentName: 'خالد ياسر', rating: 5, comment: 'شكرًا جزيلًا على هذه الدورة الممتعة.', imageId: 'testimonial-3' },
        { id: 'tr-abk-10', studentName: 'زينب عمر', rating: 4, comment: 'مدرب رائع ومادة علمية ممتازة.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't11',
    slug: 'fatima-bajaber',
    name: 'أ. فاطمة باجبير',
    field: 'التصميم والرسم',
    rating: 4.8,
    imageId: 'trainer-6',
    bio: 'مصورة ومخرجة مبدعة، متخصصة في تعليم فنون التصوير الفوتوغرافي والمونتاج السينمائي.',
    qualifications: ['شهادة في الإخراج السينمائي'],
    accreditations: [],
    coursesCount: 5,
    studentsCount: 300,
    socials: {},
    reviews: [
        { id: 'tr-fb-1', studentName: 'نورة عبدالله', rating: 5, comment: 'الأستاذة فاطمة فنانة حقيقية، دورتها كانت ملهمة جدًا.', imageId: 'testimonial-2' },
        { id: 'tr-fb-2', studentName: 'أحمد سالم', rating: 5, comment: 'تعلمت أسرار التصوير والمونتاج بفضلها.', imageId: 'testimonial-1' },
        { id: 'tr-fb-3', studentName: 'سارة علي', rating: 4, comment: 'مدربة رائعة ومتمكنة.', imageId: 'testimonial-2' },
        { id: 'tr-fb-4', studentName: 'علي محمد', rating: 5, comment: 'استفدت من كل لحظة في الدورة.', imageId: 'testimonial-3' },
        { id: 'tr-fb-5', studentName: 'فاطمة حسن', rating: 5, comment: 'أنصح بدوراتها لكل عشاق التصوير.', imageId: 'testimonial-4' },
        { id: 'tr-fb-6', studentName: 'حسن خالد', rating: 4, comment: 'تجربة تعليمية ممتعة ومفيدة.', imageId: 'testimonial-5' },
        { id: 'tr-fb-7', studentName: 'مريم أحمد', rating: 5, comment: 'أسلوبها في الشرح بسيط ومباشر.', imageId: 'testimonial-6' },
        { id: 'tr-fb-8', studentName: 'خالد عمر', rating: 5, comment: 'شكرًا أستاذة فاطمة على هذه الدورة القيمة.', imageId: 'testimonial-1' },
        { id: 'tr-fb-9', studentName: 'يوسف صالح', rating: 4, comment: 'محتوى الدورة كان ممتازًا.', imageId: 'testimonial-3' },
        { id: 'tr-fb-10', studentName: 'زينب عبدالله', rating: 5, comment: 'مدربة مبدعة بمعنى الكلمة.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't12',
    slug: 'waleed-bakarkar',
    name: 'أ. وليد باكركر',
    field: 'التصميم والرسم',
    rating: 4.9,
    imageId: 'trainer-5',
    bio: 'مصور فوتوغرافي محترف متخصص في التصوير بالجوال، يساعد الهواة على التقاط صور احترافية باستخدام أدوات بسيطة.',
    qualifications: ['ورش عمل متقدمة في التصوير'],
    accreditations: [],
    coursesCount: 15,
    studentsCount: 1000,
    socials: {},
    reviews: [
        { id: 'tr-wb-1', studentName: 'محمد خالد', rating: 5, comment: 'الأستاذ وليد حوّل طريقة تصويري بالجوال 180 درجة، شكرًا جزيلًا.', imageId: 'testimonial-3' },
        { id: 'tr-wb-2', studentName: 'آمنة علي', rating: 5, comment: 'دورة قصيرة ومكثفة لكنها مليئة بالفوائد، المدرب كان رائعًا.', imageId: 'testimonial-4' },
        { id: 'tr-wb-3', studentName: 'ياسر سالم', rating: 4, comment: 'نصائح عملية ومفيدة جدًا.', imageId: 'testimonial-5' },
        { id: 'tr-wb-4', studentName: 'فاطمة محمد', rating: 5, comment: 'لم أكن أتوقع أن أستطيع التقاط مثل هذه الصور بهاتفي.', imageId: 'testimonial-6' },
        { id: 'tr-wb-5', studentName: 'عبدالله حسن', rating: 5, comment: 'مدرب خبير ومتمكن.', imageId: 'testimonial-1' },
        { id: 'tr-wb-6', studentName: 'سارة أحمد', rating: 4, comment: 'أنصح بالدورة بشدة.', imageId: 'testimonial-2' },
        { id: 'tr-wb-7', studentName: 'علي ياسر', rating: 5, comment: 'تجربة ممتعة ومفيدة.', imageId: 'testimonial-3' },
        { id: 'tr-wb-8', studentName: 'مريم عبدالله', rating: 5, comment: 'المدرب كان صبورًا ويجيب على كل الأسئلة.', imageId: 'testimonial-4' },
        { id: 'tr-wb-9', studentName: 'خالد صالح', rating: 4, comment: 'محتوى الدورة ممتاز.', imageId: 'testimonial-5' },
        { id: 'tr-wb-10', studentName: 'نورة خالد', rating: 5, comment: 'الدورة فاقت توقعاتي.', imageId: 'testimonial-6' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't13',
    slug: 'mohsen-alattas',
    name: 'م. محسن العطاس',
    field: 'الأمن السيبراني وبرمجة الجوالات',
    rating: 4.9,
    imageId: 'trainer-7',
    bio: 'خبير في مجال الأمن السيبراني وتطوير تطبيقات الجوال، شغوف بمشاركة معرفته وتأهيل جيل جديد من المطورين والمختصين في مجال أمن المعلومات.',
    qualifications: ['ماجستير في أمن المعلومات', 'شهادة CEH (Certified Ethical Hacker)'],
    accreditations: ['CISSP', 'CompTIA Security+'],
    coursesCount: 5,
    studentsCount: 350,
    socials: {},
    reviews: [
        { id: 'tr-mha-1', studentName: 'سالم عبدالله', rating: 5, comment: 'المهندس محسن من أفضل الخبراء في مجال الأمن السيبراني.', imageId: 'testimonial-1' },
        { id: 'tr-mha-2', studentName: 'فاطمة علي', rating: 5, comment: 'دورة الأمن السيبراني كانت شاملة ومحدثة.', imageId: 'testimonial-2' },
        { id: 'tr-mha-3', studentName: 'أحمد خالد', rating: 4, comment: 'أسلوبه في الشرح مميز ويجعل المواضيع المعقدة سهلة.', imageId: 'testimonial-3' },
        { id: 'tr-mha-4', studentName: 'مريم حسن', rating: 5, comment: 'استفدت كثيرًا من خبرته العملية.', imageId: 'testimonial-4' },
        { id: 'tr-mha-5', studentName: 'علي سالم', rating: 5, comment: 'مدرب محترف ومادة علمية قوية.', imageId: 'testimonial-5' },
        { id: 'tr-mha-6', studentName: 'نورة محمد', rating: 4, comment: 'أنصح بدوراته بشدة.', imageId: 'testimonial-6' },
        { id: 'tr-mha-7', studentName: 'خالد أحمد', rating: 5, comment: 'تجربة تعليمية رائعة.', imageId: 'testimonial-1' },
        { id: 'tr-mha-8', studentName: 'سارة ياسر', rating: 5, comment: 'دورة برمجة الجوالات كانت بداية ممتازة لي.', imageId: 'testimonial-2' },
        { id: 'tr-mha-9', studentName: 'يوسف علي', rating: 4, comment: 'شكرًا للمهندس محسن.', imageId: 'testimonial-3' },
        { id: 'tr-mha-10', studentName: 'زينب خالد', rating: 5, comment: 'الدورة كانت فوق التوقعات.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't14',
    slug: 'omar-omar',
    name: 'أ. عمر عمر',
    field: 'إدارة وحاسوب',
    rating: 4.7,
    imageId: 'trainer-3',
    bio: 'مدرب متخصص في المهارات الإدارية وبرامج الحاسوب. يمتلك خبرة في تدريب الموظفين والطلاب على حد سواء لتحسين كفاءتهم في بيئة العمل.',
    qualifications: ['شهادة تدريب مدربين (TOT)'],
    accreditations: ['ICDL Certified'],
    coursesCount: 25,
    studentsCount: 1300,
    socials: {},
    reviews: [
        { id: 'tr-oo-1', studentName: 'أحمد محمد', rating: 5, comment: 'الأستاذ عمر مدرب قدير ومتمكن.', imageId: 'testimonial-1' },
        { id: 'tr-oo-2', studentName: 'فاطمة سالم', rating: 4, comment: 'دورة السكرتارية كانت عملية جدًا.', imageId: 'testimonial-2' },
        { id: 'tr-oo-3', studentName: 'علي عبدالله', rating: 5, comment: 'استفدت من خبرته في برامج الأوفيس.', imageId: 'testimonial-3' },
        { id: 'tr-oo-4', studentName: 'مريم حسن', rating: 5, comment: 'أسلوبه في التدريب رائع.', imageId: 'testimonial-4' },
        { id: 'tr-oo-5', studentName: 'خالد علي', rating: 4, comment: 'أنصح بدوراته.', imageId: 'testimonial-5' },
        { id: 'tr-oo-6', studentName: 'سارة أحمد', rating: 5, comment: 'تجربة تعليمية مميزة.', imageId: 'testimonial-6' },
        { id: 'tr-oo-7', studentName: 'يوسف خالد', rating: 4, comment: 'محتوى الدورة كان قيمًا.', imageId: 'testimonial-1' },
        { id: 'tr-oo-8', studentName: 'نورة سالم', rating: 5, comment: 'شكرًا للأستاذ عمر.', imageId: 'testimonial-2' },
        { id: 'tr-oo-9', studentName: 'سالم ياسر', rating: 5, comment: 'دبلوم الحاسوب كان شاملاً.', imageId: 'testimonial-3' },
        { id: 'tr-oo-10', studentName: 'زينب محمد', rating: 4, comment: 'مدرب محترف ومادة علمية منظمة.', imageId: 'testimonial-4' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't15',
    slug: 'maha-ghaithan',
    name: 'أ. مها غيثان',
    field: 'تطوير ذاتي وخدمة عملاء',
    rating: 4.9,
    imageId: 'trainer-2',
    bio: 'مدربة حياة معتمدة وخبيرة في تطوير الذات ومهارات التواصل. تعمل على تمكين الأفراد من تحقيق أهدافهم وبناء حياة مهنية وشخصية متوازنة.',
    qualifications: ['مدرب حياة معتمد (Certified Life Coach)'],
    accreditations: ['International Coaching Federation (ICF)'],
    coursesCount: 30,
    studentsCount: 2000,
    socials: {},
    reviews: [
        { id: 'tr-mg-1', studentName: 'فاطمة عبدالله', rating: 5, comment: 'الأستاذة مها مصدر إلهام حقيقي، أمسياتها غيرت فيني الكثير.', imageId: 'testimonial-4' },
        { id: 'tr-mg-2', studentName: 'أحمد علي', rating: 5, comment: 'دورة خدمة العملاء كانت من أفضل الدورات التي حضرتها.', imageId: 'testimonial-1' },
        { id: 'tr-mg-3', studentName: 'سارة حسن', rating: 4, comment: 'مدربة رائعة تمتلك طاقة إيجابية مذهلة.', imageId: 'testimonial-2' },
        { id: 'tr-mg-4', studentName: 'محمد سالم', rating: 5, comment: 'تعلمت منها الكثير عن تطوير الذات وتحقيق الأهداف.', imageId: 'testimonial-3' },
        { id: 'tr-mg-5', studentName: 'عائشة خالد', rating: 5, comment: 'أنصح الجميع بحضور دوراتها وأمسياتها.', imageId: 'testimonial-4' },
        { id: 'tr-mg-6', studentName: 'علي محمد', rating: 4, comment: 'تجربة فريدة ومفيدة.', imageId: 'testimonial-5' },
        { id: 'tr-mg-7', studentName: 'مريم صالح', rating: 5, comment: 'مدربة متمكنة وشغوفة بعملها.', imageId: 'testimonial-6' },
        { id: 'tr-mg-8', studentName: 'خالد عبدالله', rating: 5, comment: 'شكرًا أستاذة مها على كل شيء.', imageId: 'testimonial-1' },
        { id: 'tr-mg-9', studentName: 'نورة ياسر', rating: 4, comment: 'استفدت من كل دقيقة في الدورة.', imageId: 'testimonial-2' },
        { id: 'tr-mg-10', studentName: 'يوسف أحمد', rating: 5, comment: 'أمسية التفكير الإبداعي كانت رائعة.', imageId: 'testimonial-3' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't16',
    slug: 'fatima-bawazir',
    name: 'أ. فاطمة باوزير',
    field: 'التجميل',
    rating: 4.9,
    imageId: 'trainer-12',
    bio: 'خبيرة تجميل معتمدة بخبرة واسعة في مجال العناية بالشعر والبشرة والمكياج الاحترافي.',
    qualifications: ['دبلوم تجميل شامل'],
    accreditations: ['شهادة معتمدة من أكاديمية لوريال'],
    coursesCount: 10,
    studentsCount: 500,
    socials: {},
    reviews: [
        { id: 'tr-fbw-1', studentName: 'عائشة محمد', rating: 5, comment: 'الأستاذة فاطمة خبيرة حقيقية، دبلوم الكوافير كان شاملاً ومفيدًا.', imageId: 'testimonial-4' },
        { id: 'tr-fbw-2', studentName: 'مريم علي', rating: 5, comment: 'تعلمت منها أحدث تقنيات المكياج وتصفيف الشعر.', imageId: 'testimonial-6' },
        { id: 'tr-fbw-3', studentName: 'سارة خالد', rating: 4, comment: 'مدربة رائعة وصبورة.', imageId: 'testimonial-2' },
        { id: 'tr-fbw-4', studentName: 'فاطمة حسن', rating: 5, comment: 'أصبحت أثق بمهاراتي كمصففة شعر بفضلها.', imageId: 'testimonial-4' },
        { id: 'tr-fbw-5', studentName: 'نورة سالم', rating: 5, comment: 'أنصح بدبلوم الكوافير لكل من ترغب في دخول هذا المجال.', imageId: 'testimonial-2' },
        { id: 'tr-fbw-6', studentName: 'زينب عبدالله', rating: 4, comment: 'تجربة تعليمية ممتازة.', imageId: 'testimonial-4' },
        { id: 'tr-fbw-7', studentName: 'آمنة ياسر', rating: 5, comment: 'مدربة محترفة ومادة علمية غنية.', imageId: 'testimonial-2' },
        { id: 'tr-fbw-8', studentName: 'خديجة علي', rating: 5, comment: 'شكرًا للأستاذة فاطمة على كل المعلومات القيمة.', imageId: 'testimonial-4' },
        { id: 'tr-fbw-9', studentName: 'حصة محمد', rating: 4, comment: 'استفدت كثيرًا من التدريب العملي.', imageId: 'testimonial-6' },
        { id: 'tr-fbw-10', studentName: 'منيرة صالح', rating: 5, comment: 'الدورة كانت أفضل استثمار في نفسي.', imageId: 'testimonial-2' },
    ],
    whatsapp: '967776999568'
  }
];

export const ALL_BOOKS: Book[] = [
  {
    id: 'b1',
    slug: 'python-basics-for-beginners',
    title: 'أساسيات بايثون للمبتدئين',
    author: 'م. محمود الحساني',
    rating: 4.9,
    imageId: 'book-python',
    description: 'يهدف إلى تعليم المفاهيم الأساسية في لغة Python بأسلوب مبسط يناسب المبتدئين في عالم البرمجة.',
    topics: ['المتغيرات', 'أنواع البيانات', 'الشروط', 'التكرار', 'الدوال'],
    pages: 135,
    reviews: [
      { id: 'br1', name: 'علي حسن', rating: 5, quote: 'كتاب رائع ومباشر، ساعدني كثيرًا في فهم أساسيات بايثون.', imageId: 'testimonial-1' }
    ]
  },
  {
    id: 'b2',
    slug: 'sql-databases',
    title: 'قواعد البيانات SQL',
    author: 'م. محمود الحساني',
    rating: 4.8,
    imageId: 'book-sql',
    description: 'يتناول المفاهيم الأساسية لقواعد البيانات، وطريقة التعامل مع جمل SQL لإنشاء واستعلام وتحديث البيانات.',
    topics: ['مفاهيم قواعد البيانات', 'إنشاء الجداول', 'استعلام البيانات', 'تحديث وحذف البيانات'],
    pages: 107,
    reviews: []
  },
  {
    id: 'b3',
    slug: 'visual-programming-with-windows-forms',
    title: 'البرمجة المرئية windows forms',
    author: 'م. محمود الحساني',
    rating: 4.7,
    imageId: 'book-winforms',
    description: 'يشرح كيفية بناء تطبيقات سطح المكتب التفاعلية باستخدام واجهات Windows Forms بلغة C#.',
    topics: ['واجهات المستخدم', 'الأدوات والعناصر', 'برمجة الأحداث', 'تطبيقات عملية'],
    pages: 105,
    reviews: []
  },
  {
    id: 'b4',
    slug: 'learn-csharp-console-basics',
    title: 'تعلم أساسيات البرمجة Console (C#)',
    author: 'م. محمود الحساني',
    rating: 4.8,
    imageId: 'book-csharp',
    description: 'يركز على المفاهيم الأساسية في البرمجة باستخدام C# من خلال بيئة الكونسول، مع تطبيقات عملية وتمارين متنوعة.',
    topics: ['أساسيات C#', 'البرمجة كائنية التوجه', 'التعامل مع الملفات', 'تمارين متنوعة'],
    pages: 133,
    reviews: []
  },
  {
    id: 'b5',
    slug: 'go-go-1',
    title: 'Go Go 1',
    author: 'قسم اللغة الإنجليزية',
    rating: 4.6,
    imageId: 'book-english-1',
    description: 'مخصص للمبتدئين لتعلم المفردات الأساسية وقواعد اللغة الإنجليزية بطريقة ممتعة وتفاعلية.',
    topics: ['المفردات الأساسية', 'قواعد بسيطة', 'تمارين تفاعلية', 'بداية النطق'],
    pages: 90,
    reviews: []
  },
  {
    id: 'b6',
    slug: 'go-go-2',
    title: 'Go Go 2',
    author: 'قسم اللغة الإنجليزية',
    rating: 4.7,
    imageId: 'book-english-2',
    description: 'يطور مهارات المحادثة والاستماع والقراءة للطلاب في المستوى المتوسط.',
    topics: ['محادثات متوسطة', 'فهم المقروء', 'تمارين استماع', 'قواعد متقدمة'],
    pages: 110,
    reviews: []
  },
  {
    id: 'b7',
    slug: 'english-for-everyone',
    title: 'English for Everyone',
    author: 'قسم اللغة الإنجليزية',
    rating: 4.8,
    imageId: 'book-english-3',
    description: 'منهج شامل لتقوية المهارات اللغوية الأربع (الاستماع، القراءة، الكتابة، المحادثة) مع تمارين تطبيقية متنوعة.',
    topics: ['الاستماع', 'القراءة', 'الكتابة', 'المحادثة', 'تمارين شاملة'],
    pages: 250,
    reviews: []
  },
  {
    id: 'b8',
    slug: 'daily-english-conversations',
    title: 'Daily English Conversations',
    author: 'قسم اللغة الإنجليزية',
    rating: 4.7,
    imageId: 'book-english-4',
    description: 'يركز على العبارات اليومية والمواقف الحياتية لتقوية مهارات التحدث بطلاقة وثقة.',
    topics: ['محادثات يومية', 'عبارات شائعة', 'مواقف حياتية', 'تعزيز الثقة بالنفس'],
    pages: 120,
    reviews: []
  }
];


export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'tm1',
    name: 'أحمد ياسين',
    course: 'دورة مقدمة في الويب (HTML + CSS)',
    quote: 'كانت دورة تطوير الويب في معهد أبعاد نقطة تحول في مسيرتي. المحتوى عملي والمدرب كان خبيرًا بمعنى الكلمة. أنصح أي شخص يبدأ في البرمجة بالالتحاق بهم.',
    imageId: 'testimonial-1',
  },
  {
    id: 'tm2',
    name: 'سارة خالد',
    course: 'دبلوم الجرافيك ديزاين',
    quote: 'تعلمت الكثير في وقت قصير. البيئة التعليمية في معهد أبعاد محفزة جدًا، والمدربون كانوا ملهمين وداعمين طوال فترة الدبلوم.',
    imageId: 'testimonial-2',
  },
  {
    id: 'tm3',
    name: 'عمر الصالح',
    course: 'دورة مقدمة في إدارة المشاريع',
    quote: 'بفضل دورة إدارة المشاريع في معهد أبعاد، اكتسبت المهارات اللازمة لتنظيم عملي بفعالية أكبر. شكرًا جزيلًا لكم.',
    imageId: 'testimonial-3',
  },
  {
    id: 'tm4',
    name: 'نورة سالم',
    course: 'دورة الأمن السيبراني',
    quote: 'المحتوى في دورة الأمن السيبراني كان غنيًا جدًا والمدرب متمكن. معهد أبعاد هو المكان الأفضل لتعلم هذا المجال المهم.',
    imageId: 'testimonial-4',
  },
  {
    id: 'tm5',
    name: 'خالد عبدالله',
    course: 'دبلوم صناعة المحتوى والتسويق الرقمي',
    quote: 'دورة التسويق الرقمي كانت شاملة وعملية، وساعدتني على إطلاق حملتي التسويقية الأولى بنجاح. المدربون في معهد أبعاد خبراء حقيقيون.',
    imageId: 'testimonial-5',
  },
  {
    id: 'tm6',
    name: 'فاطمة علي',
    course: 'دورة التصميم الداخلي والديكور',
    quote: 'استمتعت بكل لحظة في هذه الدورة. تعلمت في معهد أبعاد كيف أحول المساحات العادية إلى أماكن إبداعية وجميلة. شكرًا للمهندس عادل.',
    imageId: 'testimonial-6',
  },
];

export const NEWS_ARTICLES: NewsArticle[] = [
    {
      id: 'n1',
      slug: 'new-partnership-announcement',
      title: 'معهد أبعاد يعقد شراكة استراتيجية مع أكاديمية ABC',
      date: '25 يوليو 2024',
      type: 'announcement',
      imageId: 'news-2',
      summary: 'في خطوة لتعزيز جودة التعليم، وقع معهد أبعاد اتفاقية شراكة مع أكاديمية ABC الرائدة لتبادل الخبرات وتطوير برامج مشتركة.',
      content: 'في خطوة تهدف إلى تعزيز جودة المخرجات التعليمية وتوسيع آفاق التعاون الأكاديمي، أعلن معهد أبعاد للدراسات والتدريب عن توقيع شراكة استراتيجية مع أكاديمية ABC الدولية. تتضمن هذه الشراكة تبادل الخبرات بين المدربين، وتطوير دورات تدريبية مشتركة، ومنح شهادات معتمدة من كلا الطرفين، مما يفتح فرصًا أوسع للمتدربين في سوق العمل المحلي والدولي.'
    },
    {
      id: 'n2',
      slug: 'summer-discounts-2024',
      title: 'لا تفوت عروض الصيف! خصومات تصل إلى 30% على دورات مختارة',
      date: '15 يوليو 2024',
      type: 'offer',
      imageId: 'news-3',
      summary: 'يقدم معهد أبعاد خصومات خاصة بمناسبة فصل الصيف على مجموعة من الدورات الأكثر طلباً في مجالات البرمجة والتصميم.',
      content: 'بمناسبة حلول فصل الصيف، يسر معهد أبعاد أن يعلن عن إطلاق حملة "صيفك مهارات" التي تقدم خصومات استثنائية تصل إلى 30% على باقة من الدورات التدريبية المتميزة. تشمل العروض دورات تطوير الويب، والتصميم الجرافيكي، والتسويق الرقمي. هذه فرصتكم لتطوير مهاراتكم واستثمار وقتكم بأفضل شكل ممكن. العروض سارية حتى نهاية شهر أغسطس.'
    },
    {
      id: 'n3',
      slug: 'graduation-ceremony-june',
      title: 'احتفالية تخرج دفعة يونيو 2024',
      date: '30 يونيو 2024',
      type: 'event',
      imageId: 'news-1',
      summary: 'نظم معهد أبعاد حفل تخرج بهيج لطلاب دفعة يونيو، بحضور المدربين وأهالي الخريجين.',
      content: 'في أجواء مليئة بالفخر والبهجة، احتفل معهد أبعاد بتخريج دفعة جديدة من طلابه لشهر يونيو 2024. أقيم الحفل في القاعة الرئيسية للمعهد وشهد حضورًا لافتًا من أهالي الخريجين وأصدقائهم. تخلل الحفل كلمات ملهمة من إدارة المعهد والمدربين، وتم توزيع الشهادات على الخريجين الذين عبروا عن سعادتهم وامتنانهم للتجربة التعليمية الفريدة التي حصلوا عليها.'
    },
    {
      id: 'n4',
      slug: 'student-project-showcase-july',
      title: 'عرض مشاريع تخرج طلاب دبلوم الجرافيك ديزاين',
      date: '28 يوليو 2024',
      type: 'event',
      imageId: 'news-4',
      summary: 'نظم معهد أبعاد معرضًا لمشاريع تخرج طلاب دبلوم الجرافيك ديزاين، حيث عرض الطلاب إبداعاتهم في تصميم الهويات البصرية والملصقات.',
      content: 'تألق طلاب دبلوم الجرافيك ديزاين في معرض مشاريع تخرجهم الذي أقيم في المعهد. عرض الطلاب مجموعة متنوعة من الأعمال الإبداعية التي تعكس المهارات التي اكتسبوها خلال الدورة. لاقى المعرض إعجاب الحضور من مدربين ومهتمين بمجال التصميم.'
    },
    {
      id: 'n5',
      slug: 'ai-in-design-seminar',
      title: 'أمسية حول "مستقبل التصميم في عصر الذكاء الاصطناعي"',
      date: '02 أغسطس 2024',
      type: 'announcement',
      imageId: 'news-5',
      summary: 'ينظم المعهد أمسية مجانية يقدمها الأستاذ عاهد بابعير لمناقشة تأثير الذكاء الاصطناعي على مستقبل وظائف التصميم وكيفية الاستفادة من هذه الأدوات.',
      content: 'انضموا إلينا في أمسية حوارية شيقة مع خبير التصميم أ. عاهد بابعير للحديث عن أحدث أدوات الذكاء الاصطناعي وكيف تغير من طبيعة عمل المصممين. ستكون الأمسية فرصة لاستكشاف الفرص والتحديات في هذا المجال المتطور. الدعوة عامة ومجانية.'
    },
    {
      id: 'n6',
      slug: 'first-aid-course-conclusion',
      title: 'اختتام دورة الإسعافات الأولية المكثفة بنجاح',
      date: '05 أغسطس 2024',
      type: 'event',
      imageId: 'news-6',
      summary: 'اختتمت في المعهد دورة الإسعافات الأولية المكثفة التي قدمها الدكتور علي باجامزة، حيث تلقى المشاركون تدريبًا عمليًا مكثفًا.',
      content: 'شهد معهد أبعاد اختتام دورة الإسعافات الأولية التي حظيت بإقبال كبير. عبر المشاركون عن استفادتهم الكبيرة من التدريب العملي والمحتوى الغني الذي قدمه د. علي باجامزة، مؤكدين على أهمية هذه المهارات في الحياة اليومية والمهنية.'
    }
  ];

