import type { Course, Trainer, Book, Testimonial, NewsArticle } from './types';

export const ALL_COURSES: Course[] = [
  {
    id: 'c7',
    slug: 'python-basics',
    title: 'دورة تعلم أساسيات بايثون',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['popular', 'discount'],
    imageId: 'course-programming',
    description: 'التعرف على لغة بايثون، المتغيرات، الشروط، التكرار، الدوال.',
    outline: ['مقدمة إلى لغة بايثون', 'المتغيرات وأنواع البيانات', 'العمليات الحسابية والمنطقية', 'الجمل الشرطية والتكرارية', 'الدوال والوظائف'],
    studentReviews: [],
  },
  {
    id: 'c8',
    slug: 'csharp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C#)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-programming',
    description: 'تعلم مفاهيم البرمجة باستخدام C# في بيئة الكونسول.',
    outline: ['إعداد بيئة العمل', 'أساسيات C#', 'البرمجة كائنية التوجه (OOP)', 'التعامل مع الملفات', 'مشروع تطبيقي'],
    studentReviews: [],
  },
  {
    id: 'c9',
    slug: 'sql-intro',
    title: 'دورة مقدمة في قواعد البيانات SQL',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    imageId: 'course-programming',
    description: 'مقدمة عملية في أوامر SQL الأساسية لإدارة البيانات.',
    outline: ['مفاهيم قواعد البيانات', 'لغة الاستعلام الهيكلية (SQL)', 'إنشاء وتعديل الجداول', 'الاستعلام عن البيانات (SELECT)', 'ربط الجداول (JOIN)'],
    studentReviews: [],
  },
  {
    id: 'c10',
    slug: 'windows-forms-csharp',
    title: 'دورة البرمجة المرئية باستخدام Windows Forms',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    imageId: 'course-programming',
    description: 'تصميم واجهات تطبيقات سطح المكتب باستخدام C#.',
    outline: ['مقدمة إلى Windows Forms', 'الأدوات والعناصر', 'برمجة الأحداث', 'بناء تطبيق متكامل', 'نشر التطبيق'],
    studentReviews: [],
  },
  {
    id: 'c11',
    slug: 'linux-ubuntu',
    title: 'دورة نظام التشغيل لينكس توزيعة Ubuntu',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-programming',
    description: 'أساسيات نظام التشغيل لينكس وبيئة الأوامر.',
    outline: ['تاريخ لينكس', 'واجهة سطر الأوامر (CLI)', 'إدارة الملفات والمجلدات', 'صلاحيات المستخدمين', 'البرمجة النصية (Shell Scripting)'],
    studentReviews: [],
  },
  {
    id: 'c12',
    slug: 'ms-project-intro',
    title: 'دورة مقدمة في إدارة المشاريع باستخدام Microsoft Project',
    category: 'إدارة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-management',
    description: 'تعلم التخطيط وإدارة المشاريع باحترافية عبر برنامج Microsoft Project.',
    outline: ['مبادئ إدارة المشاريع', 'واجهة Microsoft Project', 'إنشاء وتخطيط المشاريع', 'متابعة التقدم', 'إصدار التقارير'],
    studentReviews: [],
  },
  {
    id: 'c13',
    slug: 'cpp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C++)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.6,
    imageId: 'course-programming',
    description: 'مقدمة في البرمجة باستخدام لغة C++ والبرمجة الكائنية.',
    outline: ['أساسيات C++', 'المؤشرات والذاكرة', 'البرمجة الكائنية (OOP)', 'المكتبة القياسية (STL)', 'تطبيقات عملية'],
    studentReviews: [],
  },
  {
    id: 'c14',
    slug: 'web-intro-html-css',
    title: 'دورة مقدمة في الويب (HTML + CSS)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-programming',
    description: 'تعلم تصميم الصفحات وبناء مواقع ويب أساسية.',
    outline: ['بنية صفحة الويب (HTML)', 'تنسيق الصفحة (CSS)', 'التصميم المتجاوب (Responsive Design)', 'نشر موقع بسيط', 'أفضل الممارسات'],
    studentReviews: [],
  },
  {
    id: 'c15',
    slug: 'intensive-first-aid',
    title: 'دورة الإسعافات الأولية المكثفة',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: '3 أسابيع',
    rating: 4.9,
    imageId: 'course-medicine',
    description: 'تعلم التعامل مع الحالات الطارئة والإصابات البسيطة. التدريب العملي على الإسعاف الميداني والإنعاش القلبي الرئوي.',
    outline: ['تقييم الحالات الطارئة', 'التعامل مع الجروح والنزيف', 'الإنعاش القلبي الرئوي (CPR)', 'تثبيت الكسور', 'الإسعافات الأولية للحروق والاختناق'],
    studentReviews: [],
  },
  {
    id: 'c16',
    slug: 'medical-program',
    title: 'دورة البرنامج الطبي',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: 'شهران',
    rating: 4.8,
    imageId: 'course-medicine',
    description: 'برنامج متكامل لتأهيل الكوادر الطبية والإدارية في المراكز الصحية. يشمل التدريب على النماذج الطبية، استقبال المرضى، وتنظيم السجلات.',
    outline: ['إدارة المراكز الصحية', 'أساسيات استقبال المرضى', 'تنظيم السجلات الطبية', 'التعامل مع النماذج الطبية', 'مهارات التواصل مع المرضى'],
    studentReviews: [],
  },
  {
    id: 'c17',
    slug: 'medical-terminology',
    title: 'دورة المصطلحات الطبية',
    category: 'الطب',
    trainerName: 'د. معتز اليزيدي',
    trainerSlug: 'moataz-al-yazidi',
    duration: 'شهران',
    rating: 4.7,
    imageId: 'course-medicine',
    description: 'تهدف إلى تمكين المتدربين من فهم المصطلحات الطبية باللغة الإنجليزية. تدريب على النطق الصحيح وفهم السياق السريري.',
    outline: ['مقدمة في المصطلحات الطبية', 'مصطلحات أجهزة الجسم', 'مصطلحات الأمراض والعمليات', 'النطق الصحيح للمصطلحات', 'تطبيقات عملية في سياقات سريرية'],
    studentReviews: [],
  },
  {
    id: 'c18',
    slug: 'content-creation-diploma',
    title: 'دبلوم صناعة المحتوى والتسويق الرقمي',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: 'شهر واحد',
    rating: 4.9,
    tags: ['popular', 'discount'],
    imageId: 'course-marketing',
    description: 'تعلم استراتيجيات صناعة المحتوى الإبداعي. التدريب على التسويق عبر السوشيال ميديا وإدارة الحملات الرقمية.',
    outline: ['استراتيجيات المحتوى الرقمي', 'كتابة المحتوى الإبداعي', 'التسويق عبر وسائل التواصل الاجتماعي', 'إدارة الحملات الإعلانية', 'تحليل الأداء (Analytics)'],
    studentReviews: [],
  },
  {
    id: 'c19',
    slug: 'content-marketing',
    title: 'دورة التسويق بالمحتوى',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: '3 أيام',
    rating: 4.8,
    imageId: 'course-marketing',
    description: 'التعرف على أساليب كتابة محتوى تسويقي فعال. تطبيق عملي على بناء خطة محتوى لعلامة تجارية.',
    outline: ['مقدمة في التسويق بالمحتوى', 'تحديد الجمهور المستهدف', 'كتابة محتوى جذاب', 'توزيع المحتوى', 'بناء خطة محتوى'],
    studentReviews: [],
  },
  {
    id: 'c20',
    slug: 'autocad',
    title: 'دورة برنامج AutoCAD',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 4.9,
    imageId: 'course-engineering',
    description: 'تعلم أساسيات الرسم الهندسي ثنائي وثلاثي الأبعاد باستخدام AutoCAD. مشاريع تطبيقية على مخططات معمارية حقيقية.',
    outline: ['مقدمة لواجهة AutoCAD', 'أدوات الرسم ثنائي الأبعاد', 'الرسم ثلاثي الأبعاد', 'إعداد المخططات للطباعة', 'مشروع تطبيقي'],
    studentReviews: [],
  },
  {
    id: 'c21',
    slug: 'revit-lumion',
    title: 'دورة برنامج Revit + Lumion',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 5.0,
    tags: ['popular', 'discount'],
    imageId: 'course-engineering',
    description: 'تعلم تصميم النماذج ثلاثية الأبعاد باستخدام Revit. استخدام Lumion لعمل الإخراج النهائي والعروض التفاعلية للمشاريع.',
    outline: ['مقدمة في BIM و Revit', 'نمذجة العناصر المعمارية', 'التحضير للتصدير إلى Lumion', 'الإضاءة والمواد في Lumion', 'إنشاء صور ومقاطع فيديو واقعية'],
    studentReviews: [],
  },
  {
    id: 'c22',
    slug: 'interior-design-decoration',
    title: 'دورة التصميم الداخلي والديكور',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: '8 أيام',
    rating: 4.9,
    imageId: 'course-design',
    description: 'تعلم أساسيات التصميم الداخلي وتنسيق الديكور للمساحات السكنية والتجارية.',
    outline: ['مبادئ التصميم الداخلي', 'نظريات الألوان وتطبيقاتها', 'توزيع الأثاث والإضاءة', 'اختيار المواد والتشطيبات', 'مشروع تصميم متكامل'],
    studentReviews: [],
  },
  {
    id: 'c23',
    slug: 'photoshop-basics',
    title: 'دورة أساسيات الفوتوشوب',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: 'شهران',
    rating: 4.8,
    imageId: 'course-design',
    description: 'تعلم أدوات Photoshop من الصفر حتى الاحتراف. تدريب عملي على تصميم الشعارات، البوسترات، وتحرير الصور.',
    outline: ['مقدمة لواجهة فوتوشوب', 'الطبقات والأقنعة', 'أدوات التحديد والتحرير', 'تصميم الشعارات والبوسترات', 'مشاريع تطبيقية'],
    studentReviews: [],
  },
  {
    id: 'c24',
    slug: 'graphic-design-diploma',
    title: 'دبلوم الجرافيك ديزاين',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: '5 أسابيع',
    rating: 4.9,
    tags: ['popular', 'discount'],
    imageId: 'course-design',
    description: 'يشمل برامج التصميم الأساسية (Photoshop, Illustrator, InDesign). تدريب على الهوية البصرية وتصميم العلامات التجارية.',
    outline: ['أساسيات Photoshop', 'تصميم المتجهات ببرنامج Illustrator', 'تصميم المطبوعات ببرنامج InDesign', 'بناء الهوية البصرية', 'مشروع التخرج'],
    studentReviews: [],
  },
  {
    id: 'c25',
    slug: 'graphics-diploma',
    title: 'دبلوم الجرافيكس',
    category: 'التصميم والرسم',
    trainerName: 'م. أحمد بخيت',
    trainerSlug: 'ahmed-bakhit',
    duration: 'شهران',
    rating: 4.7,
    imageId: 'course-design',
    description: 'تعلم التصميم المتقدم والإخراج الإبداعي للمشاريع. يشمل التدريب على أدوات العرض الاحترافي والتصميم الإعلاني.',
    outline: ['تقنيات متقدمة في Photoshop', 'الرسم الرقمي المتقدم', 'موشن جرافيك بسيط', 'تصميم الحملات الإعلانية', 'بناء معرض أعمال احترافي'],
    studentReviews: [],
  },
  {
    id: 'c26',
    slug: 'ai-design',
    title: 'دورة التصميم بالذكاء الاصطناعي',
    category: 'التصميم والرسم',
    trainerName: 'أ. عاهد بابعير',
    trainerSlug: 'aahed-babaier',
    duration: '10 أيام',
    rating: 5.0,
    tags: ['popular'],
    imageId: 'course-cybersecurity',
    description: 'تدريب على استخدام أدوات الذكاء الاصطناعي في التصميم (Midjourney, Canva AI, Firefly). مشاريع عملية لتصميم محتوى احترافي بسرعة وابتكار.',
    outline: ['مقدمة للتصميم التوليدي', 'استخدام Midjourney لإنشاء صور', 'التصميم السريع باستخدام Canva AI', 'تحرير وتوسيع الصور مع Firefly', 'تطبيقات عملية في التسويق'],
    studentReviews: [],
  },
  {
    id: 'c27',
    slug: 'photography-editing',
    title: 'دورة فن التصوير والمونتاج',
    category: 'التصميم والرسم',
    trainerName: 'أ. فاطمة باجبير',
    trainerSlug: 'fatima-bajaber',
    duration: '6 أيام',
    rating: 4.8,
    imageId: 'course-design',
    description: 'تعلم أساسيات التصوير الفوتوغرافي والفيديو. تدريب عملي على المونتاج باستخدام برامج احترافية.',
    outline: ['أساسيات الكاميرا والإضاءة', 'قواعد التكوين في التصوير', 'مبادئ المونتاج والتحرير', 'العمل على برامج المونتاج', 'مشروع فيلم قصير'],
    studentReviews: [],
  },
  {
    id: 'c28',
    slug: 'mobile-photography',
    title: 'دورة أساسيات التصوير بالجوال',
    category: 'التصميم والرسم',
    trainerName: 'أ. وليد باكركر',
    trainerSlug: 'waleed-bakarkar',
    duration: 'يومان',
    rating: 4.9,
    imageId: 'course-design',
    description: 'تعلم كيفية التقاط صور احترافية بالجوال. نصائح في الإضاءة، الزوايا، والتحرير عبر تطبيقات الهاتف.',
    outline: ['ضبط إعدادات كاميرا الجوال', 'استغلال الإضاءة الطبيعية', 'قواعد التكوين البصري', 'تطبيقات تحرير الصور', 'جلسة تصوير عملية'],
    studentReviews: [],
  },
  {
    id: 'c29',
    slug: 'cyber-security',
    title: 'دورة الأمن السيبراني',
    category: 'الأمن السيبراني',
    trainerName: 'م. محسن العطاس',
    trainerSlug: 'mohsen-alattas',
    duration: '10 أيام',
    rating: 4.9,
    tags: ['online'],
    imageId: 'course-cybersecurity',
    description: 'مقدمة شاملة في مفاهيم الأمن السيبراني وحماية البيانات. تدريب عملي على اكتشاف الثغرات وتأمين الأنظمة.',
    outline: ['مفاهيم أساسية في الأمن السيبراني', 'أنواع الهجمات الشائعة', 'تأمين الشبكات والأنظمة', 'اكتشاف الثغرات', 'الاستجابة للحوادث الأمنية'],
    studentReviews: [],
  },
  {
    id: 'c30',
    slug: 'mobile-programming',
    title: 'دورة برمجة الجوالات',
    category: 'البرمجة',
    trainerName: 'م. محسن العطاس',
    trainerSlug: 'mohsen-alattas',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['online'],
    imageId: 'course-programming',
    description: 'تعلم أساسيات تطوير تطبيقات Android وiOS. تدريب على بناء واجهات وتوصيلها بقاعدة البيانات.',
    outline: ['مقدمة لتطوير تطبيقات الجوال', 'أساسيات تطوير Android (Kotlin)', 'أساسيات تطوير iOS (Swift)', 'بناء واجهات مستخدم تفاعلية', 'ربط التطبيق بقاعدة بيانات'],
    studentReviews: [],
  },
  {
    id: 'c31',
    slug: 'secretarial-office-management',
    title: 'دورة السكرتارية وإدارة المكاتب',
    category: 'السكرتارية',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: '10 أيام',
    rating: 4.7,
    tags: ['online'],
    imageId: 'course-management',
    description: 'تأهيل المتدربين على مهارات السكرتارية الحديثة وتنظيم المكاتب. التدريب على المراسلات وإدارة الاجتماعات وتنظيم الملفات.',
    outline: ['مهام السكرتير التنفيذي', 'إدارة الوقت وتنظيم المهام', 'فن المراسلات التجارية', 'تنظيم الاجتماعات وكتابة المحاضر', 'الأرشفة الإلكترونية والورقية'],
    studentReviews: [],
  },
  {
    id: 'c32',
    slug: 'customer-service',
    title: 'دورة خدمة العملاء',
    category: 'خدمة العملاء',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['online'],
    imageId: 'course-marketing',
    description: 'تعلم مهارات التواصل الفعّال مع العملاء وإدارة المواقف الصعبة. تطوير مهارات الإنصات واللباقة المهنية.',
    outline: ['أهمية خدمة العملاء', 'مهارات التواصل الفعال', 'التعامل مع شكاوى العملاء', 'إدارة المواقف الصعبة', 'بناء علاقات دائمة مع العملاء'],
    studentReviews: [],
  },
  {
    id: 'c33',
    slug: 'life-coach-evening',
    title: 'أمسية مدرب الحياة (Life Coach Evening)',
    category: 'التفكير الإبداعي',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: 'يوم واحد',
    rating: 4.9,
    tags: ['online'],
    imageId: 'course-women',
    description: 'أمسية تطوير ذاتي حول التحفيز والإيجابية وإدارة الحياة. تفاعلية مع جلسة أسئلة وإجابات مباشرة.',
    outline: ['مقدمة في الكوتشينج', 'تحديد الأهداف الشخصية', 'استراتيجيات التحفيز الذاتي', 'التغلب على التحديات', 'جلسة أسئلة وأجوبة'],
    studentReviews: [],
  },
  {
    id: 'c34',
    slug: 'creative-thinking-evening',
    title: 'أمسية التفكير الإبداعي',
    category: 'التفكير الإبداعي',
    trainerName: 'أ. مها غيثان',
    trainerSlug: 'maha-ghaithan',
    duration: 'يوم واحد',
    rating: 4.9,
    tags: ['online'],
    imageId: 'course-design',
    description: 'تعلم طرق التفكير خارج الصندوق وإطلاق العنان للإبداع. تطبيقات عملية وتمارين تحفيزية.',
    outline: ['ما هو التفكير الإبداعي؟', 'تقنيات العصف الذهني', 'حل المشكلات بطرق مبتكرة', 'تمارين عملية لتحفيز الإبداع', 'تطبيق الأفكار على أرض الواقع'],
    studentReviews: [],
  },
  {
    id: 'c35',
    slug: 'computer-diploma',
    title: 'دبلوم الحاسوب',
    category: 'الحاسوب',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: 'شهران',
    rating: 4.8,
    tags: ['popular', 'discount'],
    imageId: 'course-programming',
    description: 'تدريب شامل على أساسيات الحاسوب وأنظمة التشغيل وبرامج Microsoft Office. يشمل التطبيق العملي في Excel, Word, PowerPoint.',
    outline: ['مكونات الحاسوب وأنظمة التشغيل', 'إتقان برنامج Microsoft Word', 'مهارات متقدمة في Microsoft Excel', 'تصميم عروض تقديمية احترافية بـ PowerPoint', 'أمن المعلومات والإنترنت'],
    studentReviews: [],
  },
  {
    id: 'c36',
    slug: 'mayo-ketchup-course',
    title: 'دورة المايونيز والكاتشب',
    category: 'دورات نسائية',
    trainerName: 'أ. عمر عمر',
    trainerSlug: 'omar-omar',
    duration: '4 أيام',
    rating: 4.5,
    tags: ['discount'],
    imageId: 'course-women',
    description: 'دورة عملية لتعلّم طرق إعداد المايونيز والكاتشب بطرق احترافية. مناسبة لمحبات الطبخ والمشاريع المنزلية الصغيرة. تتضمن وصفات ونصائح لتغليف وتخزين المنتجات.',
    outline: ['أساسيات صنع الصلصات', 'وصفة المايونيز الكلاسيكي', 'وصفة الكاتشب المنزلي', 'نصائح التغليف والتخزين', 'أفكار لمشاريع منزلية'],
    studentReviews: [],
  },
  {
    id: 'c37',
    slug: 'hairdressing-diploma',
    title: 'دبلوم الكوافير',
    category: 'دورات نسائية',
    trainerName: 'أ. فاطمة باوزير',
    trainerSlug: 'fatima-bawazir',
    duration: 'شهران',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-women',
    description: 'تأهيل متكامل في تصفيف الشعر والعناية بالبشرة والمكياج. تدريب عملي على أحدث أدوات وصيحات الجمال. يمنح شهادة دبلوم معتمدة بعد اجتياز الاختبارات النهائية.',
    outline: ['أساسيات قص الشعر', 'تقنيات الصبغات الحديثة', 'العناية بالبشرة والمكياج', 'تسريحات المناسبات', 'إدارة صالونات التجميل'],
    studentReviews: [],
  },
  {
    id: 'c38',
    slug: 'marketing-360-diploma',
    title: 'دبلوم التسويق 360',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: '3 أسابيع',
    rating: 4.8,
    tags: ['discount', 'online'],
    imageId: 'course-marketing',
    description: 'تعلم استراتيجيات التسويق الشامل عبر المنصات الرقمية والتقليدية. تطبيق عملي على التسويق بالمحتوى والإعلانات الممولة. مناسب لرائدات الأعمال والراغبات في تنمية مشاريعهن.',
    outline: ['مقدمة في التسويق الشامل', 'استراتيجيات التسويق الرقمي', 'التسويق عبر وسائل التواصل الاجتماعي', 'الإعلانات الممولة (Google & Meta)', 'التسويق التقليدي والتكامل'],
    studentReviews: [],
  }
];

export const LATEST_COURSES = ALL_COURSES.slice(0, 3);

export const ALL_TRAINERS: Trainer[] = [
  {
    id: 't4',
    slug: 'mahmoud-alhasani',
    name: 'م. محمود الحساني',
    field: 'البرمجة',
    rating: 4.8,
    imageId: 'trainer-4',
    bio: 'مدرب برمجة متخصص في نظم المعلومات، يمتلك خبرة واسعة في بناء الأنظمة والتطبيقات. حاصل على العديد من الشهادات الدولية.',
    qualifications: ['بكالوريوس نظم معلومات'],
    accreditations: ['شهادة مطور تطبيقات من Google', 'شهادة تحليل بيانات من IBM', 'شهادة من جامعة ستانفورد', 'والعديد من الشهادات الأخرى'],
    coursesCount: 9,
    studentsCount: 850,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/mahmoud-alhasani', 
      facebook: 'https://www.facebook.com/mahmoud.alhasani',
      instagram: 'https://www.instagram.com/mahmoud.alhasani'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't5',
    slug: 'ali-bajamaza',
    name: 'د. علي باجامزة',
    field: 'الطب',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'طبيب ومحاضر متخصص في طب الطوارئ. يمتلك خبرة طويلة في تدريب الكوادر الطبية على الإسعافات الأولية والتعامل مع الحالات الحرجة.',
    qualifications: ['دكتوراة في طب الطوارئ', 'مدرب معتمد في الإنعاش القلبي الرئوي'],
    accreditations: ['البورد العربي في طب الطوارئ'],
    coursesCount: 15,
    studentsCount: 950,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/ali-bajamaza', 
      facebook: 'https://www.facebook.com/ali.bajamaza'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't6',
    slug: 'moataz-al-yazidi',
    name: 'د. معتز اليزيدي',
    field: 'الطب واللغات',
    rating: 4.8,
    imageId: 'trainer-3',
    bio: 'صيدلاني ومترجم طبي. متخصص في تدريس المصطلحات الطبية للناطقين بغير الإنجليزية، ويجمع بين الخبرة الطبية واللغوية.',
    qualifications: ['بكالوريوس صيدلة', 'دبلوم في الترجمة الطبية'],
    accreditations: ['عضو جمعية المترجمين العلميين'],
    coursesCount: 10,
    studentsCount: 700,
    socials: { 
      twitter: 'https://twitter.com/moataz-al-yazidi'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't7',
    slug: 'salem-bajulaida',
    name: 'أ. سالم باجليدة',
    field: 'التسويق',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'خبير تسويق رقمي وصانع محتوى. يساعد الشركات والأفراد على بناء حضور قوي عبر الإنترنت من خلال استراتيجيات محتوى فعالة.',
    qualifications: ['ماجستير في إدارة الأعمال (تخصص تسويق)'],
    accreditations: ['شهادة تسويق المحتوى من HubSpot', 'شهادة إعلانات Google'],
    coursesCount: 20,
    studentsCount: 1200,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/salem-bajulaida', 
      instagram: 'https://www.instagram.com/salem.bajulaida'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't8',
    slug: 'adel-al-suwail',
    name: 'م. عادل الصويل',
    field: 'الهندسة',
    rating: 4.9,
    imageId: 'trainer-4',
    bio: 'مهندس معماري ومصمم ثلاثي الأبعاد. متخصص في برامج Autodesk و Lumion، ويعمل على تدريب المهندسين على أحدث التقنيات في التصميم والإظهار المعماري.',
    qualifications: ['بكالوريوس هندسة معمارية'],
    accreditations: ['Autodesk Certified Professional (ACP)', 'Lumion Certified Expert'],
    coursesCount: 18,
    studentsCount: 800,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/adel-al-suwail', 
      website: 'https://adel-designs.com'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't9',
    slug: 'aahed-babaier',
    name: 'أ. عاهد بابعير',
    field: 'التصميم والرسم',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'مصمم جرافيك محترف بخبرة واسعة في تدريب الأفراد والشركات على أحدث برامج التصميم وأدوات الذكاء الاصطناعي.',
    qualifications: ['دبلوم عالي في التصميم الجرافيكي'],
    accreditations: ['Adobe Certified Professional'],
    coursesCount: 12,
    studentsCount: 600,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't10',
    slug: 'ahmed-bakhit',
    name: 'م. أحمد بخيت',
    field: 'التصميم والرسم',
    rating: 4.8,
    imageId: 'trainer-3',
    bio: 'مهندس ومصمم جرافيكس متخصص في التصميم المتقدم والإخراج الإبداعي. يمتلك خبرة في تدريب الطلاب على بناء محافظ أعمال احترافية.',
    qualifications: ['بكالوريوس في هندسة الوسائط المتعددة'],
    accreditations: [],
    coursesCount: 8,
    studentsCount: 450,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't11',
    slug: 'fatima-bajaber',
    name: 'أ. فاطمة باجبير',
    field: 'التصميم والرسم',
    rating: 4.8,
    imageId: 'trainer-2',
    bio: 'مصورة ومخرجة مبدعة، متخصصة في تعليم فنون التصوير الفوتوغرافي والمونتاج السينمائي.',
    qualifications: ['شهادة في الإخراج السينمائي'],
    accreditations: [],
    coursesCount: 5,
    studentsCount: 300,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't12',
    slug: 'waleed-bakarkar',
    name: 'أ. وليد باكركر',
    field: 'التصميم والرسم',
    rating: 4.9,
    imageId: 'trainer-4',
    bio: 'مصور فوتوغرافي محترف متخصص في التصوير بالجوال، يساعد الهواة على التقاط صور احترافية باستخدام أدوات بسيطة.',
    qualifications: ['ورش عمل متقدمة في التصوير'],
    accreditations: [],
    coursesCount: 15,
    studentsCount: 1000,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't13',
    slug: 'mohsen-alattas',
    name: 'م. محسن العطاس',
    field: 'الأمن السيبراني وبرمجة الجوالات',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'خبير في مجال الأمن السيبراني وتطوير تطبيقات الجوال، شغوف بمشاركة معرفته وتأهيل جيل جديد من المطورين والمختصين في مجال أمن المعلومات.',
    qualifications: ['ماجستير في أمن المعلومات', 'شهادة CEH (Certified Ethical Hacker)'],
    accreditations: ['CISSP', 'CompTIA Security+'],
    coursesCount: 5,
    studentsCount: 350,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't14',
    slug: 'omar-omar',
    name: 'أ. عمر عمر',
    field: 'إدارة وحاسوب',
    rating: 4.7,
    imageId: 'trainer-3',
    bio: 'مدرب متخصص في المهارات الإدارية وبرامج الحاسوب. يمتلك خبرة في تدريب الموظفين والطلاب على حد سواء لتحسين كفاءتهم في بيئة العمل.',
    qualifications: ['شهادة تدريب مدربين (TOT)'],
    accreditations: ['ICDL Certified'],
    coursesCount: 25,
    studentsCount: 1300,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't15',
    slug: 'maha-ghaithan',
    name: 'أ. مها غيثان',
    field: 'تطوير ذاتي وخدمة عملاء',
    rating: 4.9,
    imageId: 'trainer-2',
    bio: 'مدربة حياة معتمدة وخبيرة في تطوير الذات ومهارات التواصل. تعمل على تمكين الأفراد من تحقيق أهدافهم وبناء حياة مهنية وشخصية متوازنة.',
    qualifications: ['مدرب حياة معتمد (Certified Life Coach)'],
    accreditations: ['International Coaching Federation (ICF)'],
    coursesCount: 30,
    studentsCount: 2000,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't16',
    slug: 'fatima-bawazir',
    name: 'أ. فاطمة باوزير',
    field: 'التجميل',
    rating: 4.9,
    imageId: 'trainer-2',
    bio: 'خبيرة تجميل معتمدة بخبرة واسعة في مجال العناية بالشعر والبشرة والمكياج الاحترافي.',
    qualifications: ['دبلوم تجميل شامل'],
    accreditations: ['شهادة معتمدة من أكاديمية لوريال'],
    coursesCount: 10,
    studentsCount: 500,
    socials: {},
    reviews: [],
    whatsapp: '967776999568'
  }
];

export const ALL_BOOKS: Book[] = [
  {
    id: 'b1',
    title: 'أساسيات البرمجة بلغة Python',
    author: 'علي حسن',
    rating: 4.9,
    imageId: 'book-1',
    description: 'دليل شامل للمبتدئين لتعلم البرمجة من الصفر باستخدام لغة بايثون، إحدى أسهل وأقوى لغات البرمجة.',
    topics: ['المتغيرات وأنواع البيانات', 'الحلقات التكرارية والشروط', 'الدوال والكائنات', 'مشاريع عملية'],
    pages: 350,
  },
  {
    id: 'b2',
    title: 'سيكولوجية الألوان في التصميم',
    author: 'فاطمة الزهراء',
    rating: 4.8,
    imageId: 'book-2',
    description: 'اكتشف كيف تؤثر الألوان على المشاعر والإدراك، وتعلم كيفية استخدامها بفعالية في مشاريعك التصميمية.',
    topics: ['نظرية الألوان', 'معاني الألوان في الثقافات المختلفة', 'تطبيقات عملية في العلامات التجارية', 'أمثلة ودراسات حالة'],
    pages: 220,
  },
  {
    id: 'b3',
    title: 'دليل القائد الصغير',
    author: 'محمد عبدالله',
    rating: 4.7,
    imageId: 'book-3',
    description: 'كتاب موجه للأطفال واليافعين لتنمية المهارات القيادية مثل حل المشكلات، اتخاذ القرار، والعمل الجماعي.',
    topics: ['ما هو القائد؟', 'كيف أثق بنفسي؟', 'فن الاستماع والتواصل', 'قصص قادة ملهمين'],
    pages: 150,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'tm1',
    name: 'أحمد ياسين',
    course: 'دورة تطوير الويب الشاملة',
    quote: 'كانت الدورة نقطة تحول في حياتي المهنية. المدرب كان رائعًا والمحتوى عملي ومباشر. أنصح بها بشدة!',
    imageId: 'testimonial-1',
  },
  {
    id: 'tm2',
    name: 'سارة خالد',
    course: 'ماستر كلاس التصميم الجرافيكي',
    quote: 'تعلمت الكثير في وقت قصير. البيئة التعليمية في المعهد محفزة جدًا، والمدربة فاطمة كانت ملهمة.',
    imageId: 'testimonial-2',
  },
  {
    id: 'tm3',
    name: 'عمر الصالح',
    course: 'إدارة المشاريع الاحترافية (PMP)',
    quote: 'بفضل هذه الدورة، تمكنت من اجتياز اختبار PMP من المحاولة الأولى. شكرًا لمعهد أبعاد.',
    imageId: 'testimonial-3',
  },
];

export const NEWS_ARTICLES: NewsArticle[] = [
    {
      id: 'n1',
      slug: 'new-partnership-announcement',
      title: 'معهد أبعاد يعقد شراكة استراتيجية مع أكاديمية ABC',
      date: '25 يوليو 2024',
      type: 'announcement',
      imageId: 'news-2',
      summary: 'في خطوة لتعزيز جودة التعليم، وقع معهد أبعاد اتفاقية شراكة مع أكاديمية ABC الرائدة لتبادل الخبرات وتطوير برامج مشتركة.',
      content: 'في خطوة تهدف إلى تعزيز جودة المخرجات التعليمية وتوسيع آفاق التعاون الأكاديمي، أعلن معهد أبعاد للدراسات والتدريب عن توقيع شراكة استراتيجية مع أكاديمية ABC الدولية. تتضمن هذه الشراكة تبادل الخبرات بين المدربين، وتطوير دورات تدريبية مشتركة، ومنح شهادات معتمدة من كلا الطرفين، مما يفتح فرصًا أوسع للمتدربين في سوق العمل المحلي والدولي.'
    },
    {
      id: 'n2',
      slug: 'summer-discounts-2024',
      title: 'لا تفوت عروض الصيف! خصومات تصل إلى 30% على دورات مختارة',
      date: '15 يوليو 2024',
      type: 'offer',
      imageId: 'news-3',
      summary: 'يقدم معهد أبعاد خصومات خاصة بمناسبة فصل الصيف على مجموعة من الدورات الأكثر طلباً في مجالات البرمجة والتصميم.',
      content: 'بمناسبة حلول فصل الصيف، يسر معهد أبعاد أن يعلن عن إطلاق حملة "صيفك مهارات" التي تقدم خصومات استثنائية تصل إلى 30% على باقة من الدورات التدريبية المتميزة. تشمل العروض دورات تطوير الويب، والتصميم الجرافيكي، والتسويق الرقمي. هذه فرصتكم لتطوير مهاراتكم واستثمار وقتكم بأفضل شكل ممكن. العروض سارية حتى نهاية شهر أغسطس.'
    },
    {
      id: 'n3',
      slug: 'graduation-ceremony-june',
      title: 'احتفالية تخرج دفعة يونيو 2024',
      date: '30 يونيو 2024',
      type: 'event',
      imageId: 'news-1',
      summary: 'نظم معهد أبعاد حفل تخرج بهيج لطلاب دفعة يونيو، بحضور المدربين وأهالي الخريجين.',
      content: 'في أجواء مليئة بالفخر والبهجة، احتفل معهد أبعاد بتخريج دفعة جديدة من طلابه لشهر يونيو 2024. أقيم الحفل في القاعة الرئيسية للمعهد وشهد حضورًا لافتًا من أهالي الخريجين وأصدقائهم. تخلل الحفل كلمات ملهمة من إدارة المعهد والمدربين، وتم توزيع الشهادات على الخريجين الذين عبروا عن سعادتهم وامتنانهم للتجربة التعليمية الفريدة التي حصلوا عليها.'
    }
  ];
