import type { Course, Trainer, Book, Testimonial, NewsArticle } from './types';

export const ALL_COURSES: Course[] = [
  {
    id: 'c7',
    slug: 'python-basics',
    title: 'دورة تعلم أساسيات بايثون',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    tags: ['popular'],
    imageId: 'course-programming',
    description: 'التعرف على لغة بايثون، المتغيرات، الشروط، التكرار، الدوال.',
    outline: ['مقدمة إلى لغة بايثون', 'المتغيرات وأنواع البيانات', 'العمليات الحسابية والمنطقية', 'الجمل الشرطية والتكرارية', 'الدوال والوظائف'],
    studentReviews: [],
  },
  {
    id: 'c8',
    slug: 'csharp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C#)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-programming',
    description: 'تعلم مفاهيم البرمجة باستخدام C# في بيئة الكونسول.',
    outline: ['إعداد بيئة العمل', 'أساسيات C#', 'البرمجة كائنية التوجه (OOP)', 'التعامل مع الملفات', 'مشروع تطبيقي'],
    studentReviews: [],
  },
  {
    id: 'c9',
    slug: 'sql-intro',
    title: 'دورة مقدمة في قواعد البيانات SQL',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.8,
    imageId: 'course-programming',
    description: 'مقدمة عملية في أوامر SQL الأساسية لإدارة البيانات.',
    outline: ['مفاهيم قواعد البيانات', 'لغة الاستعلام الهيكلية (SQL)', 'إنشاء وتعديل الجداول', 'الاستعلام عن البيانات (SELECT)', 'ربط الجداول (JOIN)'],
    studentReviews: [],
  },
  {
    id: 'c10',
    slug: 'windows-forms-csharp',
    title: 'دورة البرمجة المرئية باستخدام Windows Forms',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    imageId: 'course-programming',
    description: 'تصميم واجهات تطبيقات سطح المكتب باستخدام C#.',
    outline: ['مقدمة إلى Windows Forms', 'الأدوات والعناصر', 'برمجة الأحداث', 'بناء تطبيق متكامل', 'نشر التطبيق'],
    studentReviews: [],
  },
  {
    id: 'c11',
    slug: 'linux-ubuntu',
    title: 'دورة نظام التشغيل لينكس توزيعة Ubuntu',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.7,
    imageId: 'course-programming',
    description: 'أساسيات نظام التشغيل لينكس وبيئة الأوامر.',
    outline: ['تاريخ لينكس', 'واجهة سطر الأوامر (CLI)', 'إدارة الملفات والمجلدات', 'صلاحيات المستخدمين', 'البرمجة النصية (Shell Scripting)'],
    studentReviews: [],
  },
  {
    id: 'c13',
    slug: 'cpp-console-basics',
    title: 'دورة أساسيات البرمجة Console (C++)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.6,
    imageId: 'course-programming',
    description: 'مقدمة في البرمجة باستخدام لغة C++ والبرمجة الكائنية.',
    outline: ['أساسيات C++', 'المؤشرات والذاكرة', 'البرمجة الكائنية (OOP)', 'المكتبة القياسية (STL)', 'تطبيقات عملية'],
    studentReviews: [],
  },
  {
    id: 'c14',
    slug: 'web-intro-html-css',
    title: 'دورة مقدمة في الويب (HTML + CSS)',
    category: 'البرمجة',
    trainerName: 'م. محمود الحساني',
    trainerSlug: 'mahmoud-alhasani',
    duration: '10 أيام',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-programming',
    description: 'تعلم تصميم الصفحات وبناء مواقع ويب أساسية.',
    outline: ['بنية صفحة الويب (HTML)', 'تنسيق الصفحة (CSS)', 'التصميم المتجاوب (Responsive Design)', 'نشر موقع بسيط', 'أفضل الممارسات'],
    studentReviews: [],
  },
  {
    id: 'c15',
    slug: 'intensive-first-aid',
    title: 'دورة الإسعافات الأولية المكثفة',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: '3 أسابيع',
    rating: 4.9,
    imageId: 'course-medicine',
    description: 'تعلم التعامل مع الحالات الطارئة والإصابات البسيطة. التدريب العملي على الإسعاف الميداني والإنعاش القلبي الرئوي.',
    outline: ['تقييم الحالات الطارئة', 'التعامل مع الجروح والنزيف', 'الإنعاش القلبي الرئوي (CPR)', 'تثبيت الكسور', 'الإسعافات الأولية للحروق والاختناق'],
    studentReviews: [],
  },
  {
    id: 'c16',
    slug: 'medical-program',
    title: 'دورة البرنامج الطبي',
    category: 'الطب',
    trainerName: 'د. علي باجامزة',
    trainerSlug: 'ali-bajamaza',
    duration: 'شهران',
    rating: 4.8,
    imageId: 'course-medicine',
    description: 'برنامج متكامل لتأهيل الكوادر الطبية والإدارية في المراكز الصحية. يشمل التدريب على النماذج الطبية، استقبال المرضى، وتنظيم السجلات.',
    outline: ['إدارة المراكز الصحية', 'أساسيات استقبال المرضى', 'تنظيم السجلات الطبية', 'التعامل مع النماذج الطبية', 'مهارات التواصل مع المرضى'],
    studentReviews: [],
  },
  {
    id: 'c17',
    slug: 'medical-terminology',
    title: 'دورة المصطلحات الطبية',
    category: 'الطب',
    trainerName: 'د. معتز اليزيدي',
    trainerSlug: 'moataz-al-yazidi',
    duration: 'شهران',
    rating: 4.7,
    imageId: 'course-medicine',
    description: 'تهدف إلى تمكين المتدربين من فهم المصطلحات الطبية باللغة الإنجليزية. تدريب على النطق الصحيح وفهم السياق السريري.',
    outline: ['مقدمة في المصطلحات الطبية', 'مصطلحات أجهزة الجسم', 'مصطلحات الأمراض والعمليات', 'النطق الصحيح للمصطلحات', 'تطبيقات عملية في سياقات سريرية'],
    studentReviews: [],
  },
  {
    id: 'c18',
    slug: 'content-creation-diploma',
    title: 'دبلوم صناعة المحتوى والتسويق الرقمي',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: 'شهر واحد',
    rating: 4.9,
    tags: ['popular'],
    imageId: 'course-marketing',
    description: 'تعلم استراتيجيات صناعة المحتوى الإبداعي. التدريب على التسويق عبر السوشيال ميديا وإدارة الحملات الرقمية.',
    outline: ['استراتيجيات المحتوى الرقمي', 'كتابة المحتوى الإبداعي', 'التسويق عبر وسائل التواصل الاجتماعي', 'إدارة الحملات الإعلانية', 'تحليل الأداء (Analytics)'],
    studentReviews: [],
  },
  {
    id: 'c19',
    slug: 'content-marketing',
    title: 'دورة التسويق بالمحتوى',
    category: 'التسويق',
    trainerName: 'أ. سالم باجليدة',
    trainerSlug: 'salem-bajulaida',
    duration: '3 أيام',
    rating: 4.8,
    imageId: 'course-marketing',
    description: 'التعرف على أساليب كتابة محتوى تسويقي فعال. تطبيق عملي على بناء خطة محتوى لعلامة تجارية.',
    outline: ['مقدمة في التسويق بالمحتوى', 'تحديد الجمهور المستهدف', 'كتابة محتوى جذاب', 'توزيع المحتوى', 'بناء خطة محتوى'],
    studentReviews: [],
  },
  {
    id: 'c20',
    slug: 'autocad',
    title: 'دورة برنامج AutoCAD',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 4.9,
    imageId: 'course-engineering',
    description: 'تعلم أساسيات الرسم الهندسي ثنائي وثلاثي الأبعاد باستخدام AutoCAD. مشاريع تطبيقية على مخططات معمارية حقيقية.',
    outline: ['مقدمة لواجهة AutoCAD', 'أدوات الرسم ثنائي الأبعاد', 'الرسم ثلاثي الأبعاد', 'إعداد المخططات للطباعة', 'مشروع تطبيقي'],
    studentReviews: [],
  },
  {
    id: 'c21',
    slug: 'revit-lumion',
    title: 'دورة برنامج Revit + Lumion',
    category: 'الهندسة',
    trainerName: 'م. عادل الصويل',
    trainerSlug: 'adel-al-suwail',
    duration: 'أسبوعان',
    rating: 5.0,
    tags: ['popular'],
    imageId: 'course-engineering',
    description: 'تعلم تصميم النماذج ثلاثية الأبعاد باستخدام Revit. استخدام Lumion لعمل الإخراج النهائي والعروض التفاعلية للمشاريع.',
    outline: ['مقدمة في BIM و Revit', 'نمذجة العناصر المعمارية', 'التحضير للتصدير إلى Lumion', 'الإضاءة والمواد في Lumion', 'إنشاء صور ومقاطع فيديو واقعية'],
    studentReviews: [],
  },
];

export const LATEST_COURSES = ALL_COURSES.slice(0, 3);

export const ALL_TRAINERS: Trainer[] = [
  {
    id: 't1',
    slug: 'ali-hassan',
    name: 'علي حسن',
    field: 'برمجة وطب',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'مدرب معتمد وخبير في تطوير الويب وتطبيقات الهاتف. شغوف بتبسيط المفاهيم المعقدة وجعل البرمجة في متناول الجميع. حاصل على شهادات في الإسعافات الأولية المتقدمة.',
    qualifications: ['ماجستير في علوم الحاسوب', 'شهادة مدرب معتمد من Google'],
    accreditations: ['مدرب معتمد من Microsoft', 'مدرب إسعافات أولية معتمد'],
    coursesCount: 25,
    studentsCount: 1500,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/ali-hassan', 
      twitter: 'https://twitter.com/ali_hassan', 
      facebook: 'https://www.facebook.com/ali.hassan', 
      instagram: 'https://www.instagram.com/ali.hassan' 
    },
    reviews: [
      { id: 'tr1', studentName: 'أحمد ياسين', rating: 5, comment: 'مدرب متمكن وشرحه واضح جداً. استفدت منه الكثير.', imageId: 'testimonial-1' },
      { id: 'tr2', studentName: 'نورة سالم', rating: 4, comment: 'كاريزما عالية وقدرة على إيصال المعلومة بسهولة.', imageId: 'testimonial-2' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't2',
    slug: 'fatima-alzahraa',
    name: 'فاطمة الزهراء',
    field: 'تصميم ولغات',
    rating: 4.8,
    imageId: 'trainer-2',
    bio: 'مصممة جرافيك ومترجمة لغات بخبرة تزيد عن 10 سنوات. أعمل على تمكين المتدربين من التعبير عن إبداعهم والتواصل بفعالية عبر الثقافات.',
    qualifications: ['بكالوريوس في الفنون الجميلة', 'شهادة TESOL لتدريس الإنجليزية'],
    accreditations: ['Adobe Certified Expert (ACE)', 'عضو جمعية المترجمين'],
    coursesCount: 40,
    studentsCount: 2200,
    socials: { 
      linkedin: 'https://linkedin.com/in/fatima-alzahraa', 
      website: 'https://fatima-designs.com', 
      facebook: 'https://www.facebook.com/fatima.alzahraa', 
      instagram: 'https://www.instagram.com/fatima.alzahraa' 
    },
    reviews: [
        { id: 'tr3', studentName: 'سارة خالد', rating: 5, comment: 'المدربة فاطمة رائعة وملهمة، تجعل التعلم ممتعًا.', imageId: 'testimonial-2' }
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't3',
    slug: 'mohammed-abdullah',
    name: 'محمد عبدالله',
    field: 'إدارة وأطفال',
    rating: 4.7,
    imageId: 'trainer-3',
    bio: 'استشاري إدارة مشاريع معتمد ومطور برامج تعليمية للأطفال. أؤمن بأهمية بناء جيل قيادي ومبدع منذ الصغر.',
    qualifications: ['شهادة PMP', 'دبلوم في التربية'],
    accreditations: ['Project Management Institute (PMI)', 'LEGO® Education Academy Certified'],
    coursesCount: 30,
    studentsCount: 1800,
    socials: { 
      twitter: 'https://twitter.com/mohammed_abdullah', 
      website: 'https://mohammed-abdullah.com', 
      facebook: 'https://www.facebook.com/mohammed.abdullah', 
      instagram: 'https://www.instagram.com/mohammed.abdullah' 
    },
    reviews: [
      { id: 'tr4', studentName: 'عمر الصالح', rating: 5, comment: 'خبرة كبيرة في مجاله وقدرة على تبسيط أعقد المفاهيم. شكراً مهندس محمد.', imageId: 'testimonial-3' },
    ],
    whatsapp: '967776999568'
  },
  {
    id: 't4',
    slug: 'mahmoud-alhasani',
    name: 'م. محمود الحساني',
    field: 'البرمجة',
    rating: 4.8,
    imageId: 'trainer-4',
    bio: 'مدرب برمجة متخصص في نظم المعلومات، يمتلك خبرة واسعة في بناء الأنظمة والتطبيقات. حاصل على العديد من الشهادات الدولية.',
    qualifications: ['بكالوريوس نظم معلومات'],
    accreditations: ['شهادة مطور تطبيقات من Google', 'شهادة تحليل بيانات من IBM', 'شهادة من جامعة ستانفورد', 'والعديد من الشهادات الأخرى'],
    coursesCount: 9,
    studentsCount: 850,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/mahmoud-alhasani', 
      facebook: 'https://www.facebook.com/mahmoud.alhasani',
      instagram: 'https://www.instagram.com/mahmoud.alhasani'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't5',
    slug: 'ali-bajamaza',
    name: 'د. علي باجامزة',
    field: 'الطب',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'طبيب ومحاضر متخصص في طب الطوارئ. يمتلك خبرة طويلة في تدريب الكوادر الطبية على الإسعافات الأولية والتعامل مع الحالات الحرجة.',
    qualifications: ['دكتوراة في طب الطوارئ', 'مدرب معتمد في الإنعاش القلبي الرئوي'],
    accreditations: ['البورد العربي في طب الطوارئ'],
    coursesCount: 15,
    studentsCount: 950,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/ali-bajamaza', 
      facebook: 'https://www.facebook.com/ali.bajamaza'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't6',
    slug: 'moataz-al-yazidi',
    name: 'د. معتز اليزيدي',
    field: 'الطب واللغات',
    rating: 4.8,
    imageId: 'trainer-3',
    bio: 'صيدلاني ومترجم طبي. متخصص في تدريس المصطلحات الطبية للناطقين بغير الإنجليزية، ويجمع بين الخبرة الطبية واللغوية.',
    qualifications: ['بكالوريوس صيدلة', 'دبلوم في الترجمة الطبية'],
    accreditations: ['عضو جمعية المترجمين العلميين'],
    coursesCount: 10,
    studentsCount: 700,
    socials: { 
      twitter: 'https://twitter.com/moataz-al-yazidi'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't7',
    slug: 'salem-bajulaida',
    name: 'أ. سالم باجليدة',
    field: 'التسويق',
    rating: 4.9,
    imageId: 'trainer-1',
    bio: 'خبير تسويق رقمي وصانع محتوى. يساعد الشركات والأفراد على بناء حضور قوي عبر الإنترنت من خلال استراتيجيات محتوى فعالة.',
    qualifications: ['ماجستير في إدارة الأعمال (تخصص تسويق)'],
    accreditations: ['شهادة تسويق المحتوى من HubSpot', 'شهادة إعلانات Google'],
    coursesCount: 20,
    studentsCount: 1200,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/salem-bajulaida', 
      instagram: 'https://www.instagram.com/salem.bajulaida'
    },
    reviews: [],
    whatsapp: '967776999568'
  },
  {
    id: 't8',
    slug: 'adel-al-suwail',
    name: 'م. عادل الصويل',
    field: 'الهندسة',
    rating: 4.9,
    imageId: 'trainer-4',
    bio: 'مهندس معماري ومصمم ثلاثي الأبعاد. متخصص في برامج Autodesk و Lumion، ويعمل على تدريب المهندسين على أحدث التقنيات في التصميم والإظهار المعماري.',
    qualifications: ['بكالوريوس هندسة معمارية'],
    accreditations: ['Autodesk Certified Professional (ACP)', 'Lumion Certified Expert'],
    coursesCount: 18,
    studentsCount: 800,
    socials: { 
      linkedin: 'https://www.linkedin.com/in/adel-al-suwail', 
      website: 'https://adel-designs.com'
    },
    reviews: [],
    whatsapp: '967776999568'
  }
];

export const ALL_BOOKS: Book[] = [
  {
    id: 'b1',
    title: 'أساسيات البرمجة بلغة Python',
    author: 'علي حسن',
    rating: 4.9,
    imageId: 'book-1',
    description: 'دليل شامل للمبتدئين لتعلم البرمجة من الصفر باستخدام لغة بايثون، إحدى أسهل وأقوى لغات البرمجة.',
    topics: ['المتغيرات وأنواع البيانات', 'الحلقات التكرارية والشروط', 'الدوال والكائنات', 'مشاريع عملية'],
    pages: 350,
  },
  {
    id: 'b2',
    title: 'سيكولوجية الألوان في التصميم',
    author: 'فاطمة الزهراء',
    rating: 4.8,
    imageId: 'book-2',
    description: 'اكتشف كيف تؤثر الألوان على المشاعر والإدراك، وتعلم كيفية استخدامها بفعالية في مشاريعك التصميمية.',
    topics: ['نظرية الألوان', 'معاني الألوان في الثقافات المختلفة', 'تطبيقات عملية في العلامات التجارية', 'أمثلة ودراسات حالة'],
    pages: 220,
  },
  {
    id: 'b3',
    title: 'دليل القائد الصغير',
    author: 'محمد عبدالله',
    rating: 4.7,
    imageId: 'book-3',
    description: 'كتاب موجه للأطفال واليافعين لتنمية المهارات القيادية مثل حل المشكلات، اتخاذ القرار، والعمل الجماعي.',
    topics: ['ما هو القائد؟', 'كيف أثق بنفسي؟', 'فن الاستماع والتواصل', 'قصص قادة ملهمين'],
    pages: 150,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'tm1',
    name: 'أحمد ياسين',
    course: 'دورة تطوير الويب الشاملة',
    quote: 'كانت الدورة نقطة تحول في حياتي المهنية. المدرب كان رائعًا والمحتوى عملي ومباشر. أنصح بها بشدة!',
    imageId: 'testimonial-1',
  },
  {
    id: 'tm2',
    name: 'سارة خالد',
    course: 'ماستر كلاس التصميم الجرافيكي',
    quote: 'تعلمت الكثير في وقت قصير. البيئة التعليمية في المعهد محفزة جدًا، والمدربة فاطمة كانت ملهمة.',
    imageId: 'testimonial-2',
  },
  {
    id: 'tm3',
    name: 'عمر الصالح',
    course: 'إدارة المشاريع الاحترافية (PMP)',
    quote: 'بفضل هذه الدورة، تمكنت من اجتياز اختبار PMP من المحاولة الأولى. شكرًا لمعهد أبعاد.',
    imageId: 'testimonial-3',
  },
];

export const NEWS_ARTICLES: NewsArticle[] = [
    {
      id: 'n1',
      slug: 'new-partnership-announcement',
      title: 'معهد أبعاد يعقد شراكة استراتيجية مع أكاديمية ABC',
      date: '25 يوليو 2024',
      type: 'announcement',
      imageId: 'news-2',
      summary: 'في خطوة لتعزيز جودة التعليم، وقع معهد أبعاد اتفاقية شراكة مع أكاديمية ABC الرائدة لتبادل الخبرات وتطوير برامج مشتركة.',
      content: 'في خطوة تهدف إلى تعزيز جودة المخرجات التعليمية وتوسيع آفاق التعاون الأكاديمي، أعلن معهد أبعاد للدراسات والتدريب عن توقيع شراكة استراتيجية مع أكاديمية ABC الدولية. تتضمن هذه الشراكة تبادل الخبرات بين المدربين، وتطوير دورات تدريبية مشتركة، ومنح شهادات معتمدة من كلا الطرفين، مما يفتح فرصًا أوسع للمتدربين في سوق العمل المحلي والدولي.'
    },
    {
      id: 'n2',
      slug: 'summer-discounts-2024',
      title: 'لا تفوت عروض الصيف! خصومات تصل إلى 30% على دورات مختارة',
      date: '15 يوليو 2024',
      type: 'offer',
      imageId: 'news-3',
      summary: 'يقدم معهد أبعاد خصومات خاصة بمناسبة فصل الصيف على مجموعة من الدورات الأكثر طلباً في مجالات البرمجة والتصميم.',
      content: 'بمناسبة حلول فصل الصيف، يسر معهد أبعاد أن يعلن عن إطلاق حملة "صيفك مهارات" التي تقدم خصومات استثنائية تصل إلى 30% على باقة من الدورات التدريبية المتميزة. تشمل العروض دورات تطوير الويب، والتصميم الجرافيكي، والتسويق الرقمي. هذه فرصتكم لتطوير مهاراتكم واستثمار وقتكم بأفضل شكل ممكن. العروض سارية حتى نهاية شهر أغسطس.'
    },
    {
      id: 'n3',
      slug: 'graduation-ceremony-june',
      title: 'احتفالية تخرج دفعة يونيو 2024',
      date: '30 يونيو 2024',
      type: 'event',
      imageId: 'news-1',
      summary: 'نظم معهد أبعاد حفل تخرج بهيج لطلاب دفعة يونيو، بحضور المدربين وأهالي الخريجين.',
      content: 'في أجواء مليئة بالفخر والبهجة، احتفل معهد أبعاد بتخريج دفعة جديدة من طلابه لشهر يونيو 2024. أقيم الحفل في القاعة الرئيسية للمعهد وشهد حضورًا لافتًا من أهالي الخريجين وأصدقائهم. تخلل الحفل كلمات ملهمة من إدارة المعهد والمدربين، وتم توزيع الشهادات على الخريجين الذين عبروا عن سعادتهم وامتنانهم للتجربة التعليمية الفريدة التي حصلوا عليها.'
    }
  ];
